### ISSUE TITLE
Download files via URL

### ISSUE THREAD

**Issue by RyoshiKayo** [chibisafe/chibisafe#119]
Ability to download images via URL.

**Comment by Pitu** [comment]
Use case?

**Comment by RyoshiKayo** [comment]
Saveing images from imgur/discord/giphy into albums

**Comment by Pitu** [comment]
Which you can easily achieve faster if you `Right click -> lolisafe -> upload` when you have the extension installed. I don't really see the point of this.

**Comment by RyoshiKayo** [comment]
You use a mouse on your phone? :thinking:

**Comment by BobbyWibowo** [comment]
I implemented this on mine because my upload speed was shit (tho still is)

**Comment by Pitu** [comment]
Good point @RyoshiKayo. Still seems kind of inconvenient to copy url, open lolisafe, paste and upload. Would be way better to see a small app that lets you `Share` to it and then it handles uploading directly to your lolisafe. If I find a nice way to add it to the current layout I'll work on it. I'll leave it open for now.
