### ISSUE TITLE
Integrate Universal Analytics and Measurement Protocol

### ISSUE THREAD

**Issue by Cryoplex** [chibisafe/chibisafe#15]
When files are directly viewed you're obviously unable to serve the necessary script to use analytics. Due to this inconvenience, I'd like to see [Universal Analytics and Measurement Protocol](https://github.com/peaksandpies/universal-analytics) integrated as a something easily configurable.
If you're able to confirm this is possible and that you approve of the feature, I'd be glad to put a bounty on it.
Thanks

**Comment by Pitu** [comment]
I will take a look at this and let you know if it's something we can consider as a feature, thanks!

**Comment by PascalTemel** [comment]
A little off topic, but it's great to see people willing to post bounties for this project. Thanks @Cryoplex

**Comment by alucard0134** [comment]
hey

dats preddy good
