### ISSUE TITLE
[BUG] Settings wont save in admin panel

### ISSUE THREAD

**Issue by HarryJeacock** [chibisafe/chibisafe#264]
when i go to the admin panel and enable something then refresh it resets back to previous settings.

**Comment by Pitu** [comment]
Currently saving settings from the admin panel is not implemented. As it stands, you need to edit the generated `.env` file, run `yarn build` or `npm run build` again and restart the instance for the changes to have effect. Sorry for the troubles!

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
