### ISSUE TITLE
[BUG] Session closes after refreshing the page

### ISSUE THREAD

**Issue by r33int** [chibisafe/chibisafe#269]
**Describe the bug**
When refreshing the page, the user gets instantly logged out. The session is not being remembered at all.
The worst part is that I have ABSOLUTELY no idea what is causing that. I am using node v14.16.0 on Debian 10, as well as the systemd service and nginx configuration from this repo. This issue happesns on every browser, with cookies all cleared.
I tried compltely reinstalling my VM. It kept happening, until I changed its IP address (?). After the address of the host has changed, it stopped happening for a while, but, as soon as I ran another instance on this host (with a different listen port), the issue appeared again on both instances.

**To Reproduce**
- Log in
- Refresh the page

**Expected behavior**
The session should be persistant, and the user should stay logged in after refreshing the page.

**Screenshots**
https://user-images.githubusercontent.com/22567851/113635078-4438aa80-9670-11eb-9292-136f36f09703.mp4

**Additional context**
I really have no idea on how to look for logs. NGINX does not return anything. chibisafe does not return anything. The browser console does not return anything too.
If needed, I can give a temporary access to my instance, so you can see the issue by yourself.
I've spent countless hours reinstalling my host over and over, carefully following the steps in the readme, without luck. I would really appreciate any help. 
Thank you

**Comment by Pitu** [comment]
I've never seen this happen before. You say it "fixed" itself for some time after you changed IP, but after you added another instance it started happening again. 
I have absolutely no idea how to even begin troubleshooting this, but let's give it a try.

Go to your chibisafe instance and log in. After you do that please open devtools > application > cookies > chibisafe. Do you see a cookie named `token` with a value? If so, please refresh and check if it's still there or if it's gone right after refresh, and if it's there check if the value changed at all.

**Comment by r33int** [comment]
Hi, after even further tinkering, I noticed that it happens only when there are both A and AAAA (IPv4 and IPv6) DNS records on the chibisafe instance. This is really weird. Keeping only one record and proxying using Cloudflare mitigates the issue.
About the cookie, the token does not seem to change on refresh.

**Comment by Pitu** [comment]
If the cookie is still there and doesn't change then the issues is likely not with Chibisafe but with however you are implementing your server or DNS as you pointed out. If it's fixed by proxying through CloudFlare then there's something in your box config that is messing with it.
Not sure how to further help in this case; if there are any other tests or scenarios that can help figure out a bit more why it's happening please post them here.

**Comment by r33int** [comment]
Thanks a lot for trying to help me out. Actually, this seems to happen only when a record with a NATed IPv4 address is present.
To summarize:

- NATed A record only ❌
- AAAA record only ✔
- NATed A record and AAAA record ❌

I am really confused about this situation, but if anyone can reproduce the issue and wants to look at it...

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
