### ISSUE TITLE
[FEATURE REQUEST] S3-compatible storage driver

### ISSUE THREAD

**Issue by Proxymiity** [chibisafe/chibisafe#280]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the option to select a S3-like storage system for servers that doesn't have enough space.

**Describe the solution you'd like**
Uploading to Chibisafe would upload the file to a S3 bucket, and give the direct link to access that file from the bucket.
For example, uploading `example.png` would upload it and give a link such as `https://s3.eu-west-3.amazonaws.com/chibisafe/olsJGd0a.png`

**Additional context**
It would be great to be compatible with Minio ([path-like URLs, even if Amazon is currently deprecating path-like urls](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html)). 

EDIT: current workaround I've found is to mount the S3 bucket locally. A bit tricky

**Comment by Pitu** [comment]
While this is a nice feature it's not something that I'll support anytime soon. 
I think the way you solved it is for the time being the best solution, and to give you some insight into what other people tried in the past, there is a common practice to symlink the `uploads` folder to another drive.

What I'm trying to say here is that it's not impossible to achieve as long as the users do it in their boxes, so for now the current functionality is the only thing we're planning on supporting.

**Comment by Proxymiity** [comment]
I see. Using S3FS is great enough though.

Is there a way to change (or even hardcode, doesn't matter) a new URL for uploads? Would be nice to be able to change the link displayed for images to point to the S3 bucket directly:
![](https://i.iya.at/chrome_fj4UNg.png)

**Comment by Aareksio** [comment]
You could probably configure your nginx instance to redirect (or even proxy) to s3.

**Comment by Proxymiity** [comment]
> You could probably configure your nginx instance to redirect (or even proxy) to s3.

Yeah... I could detect access to files and redirect users to the bucket or use mod_substitute in Apache. Thing is, it might be easier to hardcode than do some regex at proxy-level.

**Comment by Pitu** [comment]
You could edit this line https://github.com/WeebDev/chibisafe/blob/master/src/api/utils/Util.js#L110 and hardcode your bucket URL in there for the time being

**Comment by lazee486** [comment]
my 2c, check out rclone, lets you use s3/onedrive/mega/ pretty much any backend as a mounted share on your server, even encrypt on remote, merge endpoints...very flexible and independent, you can mount a 1tb wasabi or a 1tb onedrive... then use for multiple services.

**Comment by Pitu** [comment]
Implemented in https://github.com/chibisafe/chibisafe/pull/545
