### ISSUE TITLE
[FEATURE REQUEST] Links for registrations 

### ISSUE THREAD

**Issue by Haydman** [chibisafe/chibisafe#284]
**Is your feature request related to a problem? Please describe.**
It can be useful for closed registration and you will not need to create an account yourself for person

**Describe the solution you'd like**
Imagine a button which creates a link to register an account for a person by himself.
It can be random link for example https://site.com/reg/xxxxx

**Additional context**
Maybe that not important but for closed regs it would be great if you use chibisafe for a limited circle of people

**Comment by Pitu** [comment]
This has been added in today's commit https://github.com/chibisafe/chibisafe/pull/344/commits/d6849d15a26bf77a41e78a0bd08a90240ad39404
Keep in mind this is not yet merged to master so it will take a bit longer to get there, but it exists as a feature now.
