### ISSUE TITLE
[BUG] Original album file count persists after deleting files

### ISSUE THREAD

**Issue by ewendlick** [chibisafe/chibisafe#286]
**Describe the bug**
Original album file count persists after deleting files

**To Reproduce**
1. Create an album
2. Upload X files to the newly-created album
3. Delete Y files from the album
4. Navigate to "Home"
5. Note that the file count is X but it should be (X - Y) (see screenshot 1)
6. Navigate to the final page(s) of the album
7. If a sufficient number of files had been deleted (Y > 50), the final pages of the album may be empty (see screenshot 2)

**Expected behavior**
The file count should reflect the current number of files in the album

**Screenshots**
1
![image](https://user-images.githubusercontent.com/1897597/126884587-21cee074-4140-4790-ac59-976e59783563.png)
2
![image](https://user-images.githubusercontent.com/1897597/126884597-c5024169-0dbc-4896-9fa1-c061af50861d.png)

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
