### ISSUE TITLE
[FEATURE REQUEST] Display error message to user on registration error

### ISSUE THREAD

**Issue by ewendlick** [chibisafe/chibisafe#287]
**Is your feature request related to a problem? Please describe.**
Display error message to user on registration error

**Describe the solution you'd like**
When the server returns a 400 upon new user registration or when a user uses invalid input, display the error to the user (e.g. "A username must contain between 4-32 characters")

**Comment by Pitu** [comment]
This has been addressed in the new feature branch being worked on https://github.com/chibisafe/chibisafe/pull/344
