### ISSUE TITLE
[FEATURE REQUEST] Loading spinners

### ISSUE THREAD

**Issue by ewendlick** [chibisafe/chibisafe#288]
**Is your feature request related to a problem? Please describe.**
Interaction with the UI does not result in indication of interaction.

**Describe the solution you'd like**
Loading spinners when album pages are changed (see screenshot 1), and when albums are expanded to show more details (see screenshot 2)

**Additional context**
1
![image](https://user-images.githubusercontent.com/1897597/126884699-6a1d6bee-ae81-4b13-846a-1fccb477608d.png)
2
![image](https://user-images.githubusercontent.com/1897597/126884693-2b4a81ab-f817-4ae2-a701-e756abf44129.png)

**Comment by Pitu** [comment]
As the site has changed drastically since this was suggested I'm closing it
