### ISSUE TITLE
[BUG] Linked albums appear to be empty

### ISSUE THREAD

**Issue by ewendlick** [chibisafe/chibisafe#289]
**Describe the bug**
When using an album link (e.g. https://mysite.com/a/d4627l), the resulting page displays a message that says that the album is empty.

**To Reproduce**
1. Create an album
2. Upload images to the album
3. Create a link to the album
4. Access the created link in the browser

**Expected behavior**
The contents of the album should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/1897597/126884965-be4b6880-816d-4b69-8949-4aaccdaf7a42.png)

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
