### ISSUE TITLE
[BUG] Created album links lack domain information

### ISSUE THREAD

**Issue by ewendlick** [chibisafe/chibisafe#290]
**Describe the bug**
The album links do not include domain information and are therefore invalid.

**To Reproduce**
1. Navigate to the "Albums" page
2. Click on the expand icon for an album
3. Click on the green "Create new link" button
4. Examine the contents of the displayed link and notice that it lacks domain information

**Expected behavior**
A valid URL with domain information should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/1897597/126885035-4d1cc0bc-a8c3-4530-be9e-d5d706d47d52.png)

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
