### ISSUE TITLE
[FEATURE REQUEST] Content Security Policy does not work due to a single inline script

### ISSUE THREAD

**Issue by fourilent** [chibisafe/chibisafe#295]
**Is your feature request related to a problem? Please describe.**
I am trying to implement CSP onto my chibisafe instance, but there is one inline script which causes issues with using the website if blocked by CSP.
I'm not very good at coding but I did some digging around the code and I think its the Vuex store function that's loaded inline.

**Describe the solution you'd like**
Perhaps there's a way to make it so it loads from a script file like the rest of the scripts (eg. `<script src="/_nuxt/d2a22de.js" defer=""></script>`)? Or maybe cookies could be used.

**Additional context**
An example of the inline script causing issues with CSP:
`<script>window.__NUXT__=(function(a,b,c){return {layout:"default",data:[{}],fetch:[],error:a,state:{admin:{users:[],user:{id:a,username:a,enabled:b,createdAt:a,editedAt:a,apiKeyEditedAt:a,isAdmin:a,files:[]},file:{},settings:{},statistics:{},settingsSchema:{type:a,keys:{}}},albums:{list:[],isListLoading:b,albumDetails:{},expandedAlbums:[],tinyDetails:[]},alert:{message:a,type:a,snackbar:b},auth:{loggedIn:b,user:{id:a,isAdmin:b,username:a},token:a},config:{development:b,version:"v4.0.2",URL:"https:\u002F\u002Fu.frlt.one",baseURL:"https:\u002F\u002Fu.frlt.one\u002Fapi",serviceName:"Toshokan",maxUploadSize:1024,chunkSize:90,publicMode:b,userAccounts:b,filenameLength:c,albumLinkLength:c},images:{files:[],isLoading:b,pagination:{page:1,limit:50,totalFiles:0},search:"",showList:b,albumName:a,albumDownloadEnabled:b,fileExtraInfoMap:{},fileAlbumsMap:{},fileTagsMap:{}},tags:{tagsList:[]}},serverRendered:true,routePath:"\u002F",config:{}}}(null,false,6));</script>`

**Comment by Pitu** [comment]
This probably isn't an issue anymore with the current version
