### ISSUE TITLE
[FEATURE REQUEST] Purge/delete files of anon uploads

### ISSUE THREAD

**Issue by AruMoon** [chibisafe/chibisafe#297]
**Is your feature request related to a problem? Please describe.**
I wanna open my own instance for anyone, but it's not possible to delete some files or purge all anonymously uploaded files. It's needed for example deleting unnecessary files or cleaning storage.
Also it's not possible to do this via API, because anonymously uploaded files doesn't have owner id and it throws error

**Describe the solution you'd like**
Add page or update `Users` page to manage anonymously uploaded files.
And do fix API for purge possibility by admins

**Comment by Pitu** [comment]
This is already implemented in the current version
