### ISSUE TITLE
[FEATURE REQUEST] Autodelete timers

### ISSUE THREAD

**Issue by AruMoon** [chibisafe/chibisafe#298]
**Is your feature request related to a problem? Please describe.**
As being a free self-hosted files hosting service, storage on public instances fills up

**Describe the solution you'd like**
Setting to autodelete old files uploaded some time ago and/or timers for doing that without admins

**Additional context**
Autodelete files after some time examples: https://transfer.sh/ https://0x0.st/

**Comment by CyberiumShadow** [comment]
Duplicate of #30
