### ISSUE TITLE
[FEATURE REQUEST] A malware/NSFW scanner

### ISSUE THREAD

**Issue by abcdan** [chibisafe/chibisafe#303]
**Is your feature request related to a problem? Please describe.**
It would be great if there was an opional way to automaticallyt scan the uploaded content to saferty for the users that receive the links to the files.

**Describe the solution you'd like**
A service like https://unscan.co or https://nsfw.rest integrated

**Additional context**
I've been working on the two services for the past months and I'd love to help integrate it :) _opened this issue to see if people are interested in the feature_

**Comment by yesBad** [comment]
Sounds nice, but probably would need some sort of admin switch.

**Comment by Aareksio** [comment]
I'd advise against using external public services for this kind of job, unless done in explicit plugin-like fashion. It is a matter of the time until the compatibility breaks. 

Also rate limits, retries, queues, all the stuff required for reliable use of 3rd party API is quite complicated.

**Comment by abcdan** [comment]
> Sounds nice, but probably would need some sort of admin switch.

That's what I was thinking about, some sort of default off type thing.



> I'd advise against using external public services for this kind of job, unless done in explicit plugin-like fashion. It is a matter of the time until the compatibility breaks.
> 
> Also rate limits, retries, queues, all the stuff required for reliable use of 3rd party API is quite complicated.

Good point, I'll look into making it possible to have it as some sort of plugin that queues the file requests and we'll just see if people like the implementation in a pr

**Comment by VottonDev** [comment]
I might open a pull request for this, could use ClamAV maybe? Not necessarily the best at detecting everything but would be a rather localised solution set as false/off by default.

**Comment by Pitu** [comment]
@lazee486 you can definitely use clamav on the path, just keep in mind that if a file is infected and quarantined/deleted, it will show up on the dashboard since the database entry is still there.

**Comment by Pitu** [comment]
There are currently no plans on the roadmap to integrate this. Will reopen if that changes.
