### ISSUE TITLE
[BUG] MySQL Settings-Entries get duplicated...

### ISSUE THREAD

**Issue by calvinthefreak** [chibisafe/chibisafe#325]
**Describe the bug**
Following: I want to change the settings of my instance, in the way of try and error to replace the values in the Database, I restarted the container several times... The weird thing, that I did notice is that EVERY time I restart the stack, the Entries in the settings table get reinserted... but the old ones not truncated...

**To Reproduce**
1. Setup Chibisafe with MySQL.
2. Start it.
3. Stop it.
4. Start it.
5. look into your MySQL Server: SELECT * FROM settings; 
![image](https://user-images.githubusercontent.com/5560381/158024686-620aaa39-a713-4998-b5dc-20851728dd89.png)

**Expected behavior**
That if I set ENV "OVERWRITE_SETTINGS" to False, that nothing in the Database gets reentered or changed....

**Screenshots**
see above.

**Additional context**
For that Paranoia folks: Yes, I did open port 3306 for my database. No, I am not at risk because there is still an hardware-firewall in front of my host.

**Comment by calvinthefreak** [comment]
And yes, I did nothing else to the settings, I just filled out the docker-compose.yml from the docker/docker-compose.yml and pulled it up with docker-compose -f docker/docker-compose.yml buld & up

**Comment by calvinthefreak** [comment]
Temporary workaround is, to set a PrimaryKey to the Database, so it CANNOT enter mutliple values... hopefully this will work:

```sql
CREATE TABLE `settings` (
  `key` varchar(255) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

Sadly this will not fix the Issue mentioned in #294

**Comment by Pitu** [comment]
Thank you for bringing this up, I'll look into it 🙏

**Comment by reeve567** [comment]
Adding that this also happens in SQLite

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
