### ISSUE TITLE
[FEATURE REQUEST] Add easy docker-compose/docker cli installation methods / Add image to Docker Hub

### ISSUE THREAD

**Issue by AuthorShin** [chibisafe/chibisafe#331]
Hello
When will you consider adding the docker image to hub.docker.com?
Can you please add/make docker-compose/docker cli installation methods so that we can install chibisafe via docker management services like casaOS and Portainer?

**Comment by LostAndDead** [comment]
I would also like this, i deploy docker images using portainer and this would make my life so much easier if I could just use a compose file and set the env variables, pull the image and get it going without having to build it locally

**Comment by Pitu** [comment]
Streamlined docker support is coming in the next version which we're working hard on at the moment

**Comment by AuthorShin** [comment]
Great to here that, thank you for all the hard work.

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
