### ISSUE TITLE
[BUG] New installs of Chibisafe are currently not possible with normal instructions

### ISSUE THREAD

**Issue by BenjaminZehowlt** [chibisafe/chibisafe#358]
**Describe the bug**
New installations of Chibisafe are currently unable to be done due to a breaking change upstream from the package @nuxt/ufo being renamed in minor revision. https://github.com/unjs/ufo/commit/08d986846fdf4fc089a09eaa1582be5297d6ba7f

**To Reproduce**
1. Clone repo
2. Run npm i
3. Run setup
4. Try starting Chibisafe and the nuxt cli will fail to compile components due to breaking changes.

**Expected behavior**
Chibisafe is able to compile components and start.

**Screenshots**
N/A

**Additional context**
This can be temporarily worked around using yarn v3 and pinning @nuxt/ufo to v0.5.2
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by Pitu** [comment]
Do you know if pinning a specific nuxt version could solve this issue so that I can push a fix for it?

**Comment by BenjaminZehowlt** [comment]
Pinning a specific version of nuxt won't work due to them specifying "^0.5.0" far as I'm aware. What makes this more difficult is it's a transitive dependency.

On that note npm does have an overrides function but that did not work at all.

The only way I've been able to get it to work so far was using yarn v3 for the package manager

**Comment by Mega-Bits** [comment]
> Pinning a specific version of nuxt won't work due to them specifying "^0.5.0" far as I'm aware. What makes this more difficult is it's a transitive dependency.
> 
> On that note npm does have an overrides function but that did not work at all.
> 
> The only way I've been able to get it to work so far was using yarn v3 for the package manager

How exactly do you make this work?
I am using a node container on v14.21.3 with yarn on v1.22.5. I dont know where the change is needed.

**Comment by BenjaminZehowlt** [comment]
First, add the following above dependencies in package.json
`
        "resolutions": {
                "@nuxt/ufo": "0.5.2"
        },
`

Second run `yarn set version stable`

Third run `yarn install`

Lastly, modify the pm2.json to run `yarn` instead of `npm`

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
