### ISSUE TITLE
 restricted account issue

### ISSUE THREAD

**Issue by killforby** [chibisafe/chibisafe#364]
Hello, I can't get access to chibisafe from my unraid server, I created a template from your directory. It is impossible to access my account because "This site has disabled public uploads. You need an account. " . what is the procedure to follow to be able to access it?

![image](https://user-images.githubusercontent.com/94224508/222116711-d068b067-dec8-41ea-8275-871590a70fa1.png)

**Comment by rossiscool123** [comment]
Hello @killforby 
I think you've already asked this in the Discord but I'll respond to your issue on GitHub. You need to change the following value to true in the docker template on unRAID. Like so. 
![image](https://user-images.githubusercontent.com/62076535/222868184-0afa9574-4338-4702-b96b-fa4fc350cf34.png)
You can also edit it by signing into the admin account using the default login "admin" for both username and password.

Hope this helps. :)

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.
