### ISSUE TITLE
[FEATURE REQUEST] Collaborative curation

### ISSUE THREAD

**Issue by JediMaster25** [chibisafe/chibisafe#367]
Chibisafe is a powerful and versatile file uploader service that enables users to upload various file types with ease. To make the platform more robust, I would like to propose the addition of a collaborative curation feature.

This feature would allow users to edit file tags, albums, and more, with the ability to vote on other users' edits. Edits would automatically be approved when they reach a configurable limit of positive votes or when moderators approve them.

The collaborative curation feature would make it easier to curate files and albums on the platform, leading to more complete albums and less duplication. By allowing users to edit files in albums, there would be less need for multiple incomplete albums, and files could be marked as belonging to multiple albums.

This feature would make Chibisafe a more community-driven platform, giving users the ability to collaborate and improve the overall quality of the content on the platform. It would also help streamline the curation process, making it more efficient for moderators and users alike.

In addition to the above, I suggest adding a feature to track the edit history of files, so that users can see who made what changes to a particular file, when those changes were made, and what the changes entailed. This would help prevent malicious edits and promote transparency and accountability on the platform.

Overall, the collaborative curation feature would make Chibisafe a more dynamic and engaging platform, encouraging users to take an active role in curating and organizing the content on the platform.

For an example implementation see [stash-box](https://github.com/stashapp/stash-box).

**Comment by Pitu** [comment]
Hey thanks for reaching out.
I'm not sure the feature you are talking about really fits the core concept of chibisafe; which is being a vault for your files. While reading your post I couldn't help myself from thinking that you were talking about something like a [booru image board](https://gist.github.com/lxfly2000/c183fcd23cfb447b2b9cb353e103c8fe#image-board), which chibisafe is not. The files you upload are yours and no one else, completely private.

That being said and while you do have the ability to share files by putting them in an album and creating a public link to said album, there is no such thing as publicly browsing all the uploads to the service and decide to edit/tag them.

While being able to invite another user to collaborate on adding files to an album is something we're looking down to implement down the road, it feels to me that its vastly different from what you are proposing, unless I got what you mean wrong.

The point is, each user has their files, their albums and their tags, there is no centralized tag repository to choose from like on those sites I mentioned above, so I don't see how this could fit into the current schema of the application.

**Comment by JediMaster25** [comment]
Oh I thought this was like a self-hosted booru image board but if I have to share each album's link independently then I can't use it like that. What popular program is chibisafe an alternative to?

**Comment by 8ullyMaguire** [comment]
Hello, I'd like to reiterate the value of this feature and kindly request reconsideration.

The use case I envision involves sharing a Chibisafe instance with a group of people, granting them the ability to upload files, approve files, add tags, approve tags, and manage both private and public collections. This collaborative approach would prevent the creation of numerous, similar incomplete collections. Users could earn points for their contributions, which could then be used for resource-intensive tasks such as loading files, searching, and filtering. By incorporating safeguards like edit histories and moderator approvals, quality control would be maintained.

Configurable settings for vote thresholds and resource-intensive task costs would ensure that the default behavior remains unchanged. This proposed feature would create a unique blend of elements from InternetArchive, MusicBrainz, and Stash-Box. If multiple users were to open their instances to the public, the project would gain significant exposure, benefiting both public instance users and those who prefer private use.

By implementing the collaborative curation feature, Chibisafe would become an even more powerful and versatile platform, attracting a wider audience and fostering a thriving community.

**Comment by Pitu** [comment]
As I mentioned before, we feel this escapes completely the chibisafe scope. While some collaborative features are being considered for the future, like having multiple users contribute to an album, what you suggest goes way past that.

We might reconsider in the future, but for now this is not happening.
