### ISSUE TITLE
[FEATURE REQUEST] Apache2 

### ISSUE THREAD

**Issue by alx-xlx** [chibisafe/chibisafe#377]
**Is your feature request related to a problem? Please describe.**
Currently it looks like only nginx is supported, there are more apache2 servers so it is really hard to deploy another server with a different server type

**Describe the solution you'd like**
Support for Apache2 Server is very necessary. Current state of Chibisafe doesn't seem to work with it. Also support for Raspberry Pi is also a must

**Additional context**
Support for low powered system like pi will bring in more users flocking to this service. Chevereto has gone into paid mode. There is a void that chibisafe can fill.

**Comment by Pitu** [comment]
Nginx/Apache/Caddy is only necessary if you plan on using a domain with chibisafe.
If that's the case then you can check how to run a reverse proxy with Apache and that should be enough to get chibisafe out to the world. If you plan on accessing by IP directly then you don't need anything.

Regarding the RaspberryPI, I believe the version being developed right now works well with it, I'll do some testing in a few days.
