### ISSUE TITLE
Request for Step-by-Step Documentation to Set Up chibisafe clone

### ISSUE THREAD

**Issue by 7zx** [chibisafe/chibisafe#380]
Dear dev,

I hope this message finds you well. I am currently attempting to set up a clone of your GitHub repository, chibisafe, but I am encountering some difficulties. I apologize for any inconvenience caused by reaching out directly, but I was wondering if you could provide me with detailed step-by-step documentation to assist me in this process.

While I have some experience with Git and GitHub, I would greatly appreciate having a comprehensive guide that covers the necessary steps to successfully clone and set up the repository on my local machine. I believe having such documentation would not only benefit me but also potentially help other users who might encounter similar challenges.

If you have already prepared documentation or if there are existing resources available, I kindly request your guidance in directing me to them. Alternatively, if such documentation does not exist, I would be grateful for any instructions or tips you can provide to facilitate the cloning process.

Thank you very much for your attention to this matter. I truly appreciate your time and expertise. Please let me know if there is any additional information I can provide or if you require further clarification regarding my query.

Looking forward to your response.

Best regards,
7zx

**Comment by Pitu** [comment]
I'm closing this since the new version was just pushed to master.

**Comment by 7zx** [comment]
Thank you so much!
