### ISSUE TITLE
[QUESTION] How to use with postgresql?

### ISSUE THREAD

**Issue by killforby** [chibisafe/chibisafe#398]
Hello, how to use chibisafe with postgresql? I tried via docker on unraid and it doesn't work with postgresql? Do you have an idea?

**Comment by rossiscool123** [comment]
Also looking for this as well but considering it was just released after a massive rework I'm sure if its not implemented its coming soon.

**Comment by killforby** [comment]
yes I would really like chibisafe to work with postgresql. Have you managed to put the v5 of chibisafe

**Comment by Rake01** [comment]
It's not officially supported, but you can modify the [prisma schema](https://github.com/chibisafe/chibisafe/blob/master/packages/backend/src/prisma/schema.prisma) to use [PostgreSQL](https://www.prisma.io/docs/concepts/database-connectors/postgresql). Again, this is _not_ officially supported. I have tested with MySQL and it seems to work fine.

**Comment by Pitu** [comment]
As @Rake01 said, you could try changing the schema to use postgresql but I can't guarantee everything will work since there may be a difference with data types.

If you manage to get it working please let us know for future reference in the docs!
