### ISSUE TITLE
[BUG] Drag and drop not working/implemented. :)

### ISSUE THREAD

**Issue by rossiscool123** [chibisafe/chibisafe#399]
**Describe the bug**
Drag and drop is either broken or not implemented in the new re-write of Chibisafe
**To Reproduce**
Go to the homepage as a signed in user.
Attempt to drag and drop a file into the box marked for uploading.
Image/File opens in a new tab.

**Expected behavior**
Once a drag a file inside the marked box I expect a progress bar, file name and a URL hyperlink to the image directly.
**Screenshots**
https://github.com/chibisafe/chibisafe/assets/62076535/3f210ddd-56c7-4604-82a9-6aef9bf6ece9

**Additional context**

**Comment by pilar6195** [comment]
Yeah, that is something that was overlooked. Has been fixed and awaiting to be merged into main branch.
