### ISSUE TITLE
[FEATURE REQUEST] Embed AV1/No file size limit for Discord

### ISSUE THREAD

**Issue by Ollie1101** [chibisafe/chibisafe#405]
**Is your feature request related to a problem? Please describe.**
not being able to embed videos over 50/100mb is silly, especially when you cant use the AV1 codec. adding just a tiny couple of headers will allow discord to embed anything, refer to https://gist.github.com/Clybius/103bdf0ebde254c348e38f023191f494

much appreciated as a toggleable option.

**Comment by Pitu** [comment]
We won't be moving forward with this for the time being.
