### ISSUE TITLE
[BUG] Unauthorized Removal of "main/owner" Admin by Newly Appointed Admin

### ISSUE THREAD

**Issue by 7zx** [chibisafe/chibisafe#420]
**Describe the bug**
When the admin of the Chibisafe instance grants admin privileges to another user, the newly appointed admin has the ability to demote the "main/owner" admin of the instance.

**To Reproduce**
Log in as the current admin of the Chibisafe instance.
Go to the user settings section.
Grant admin privileges to another user.
Log in as the user who just received admin privileges.
Access the user settings.
Attempt to demote the "main/owner" admin of the instance.
Observe that the "main/owner" admin can be removed/demoted successfully.

**Expected behavior**
The newly appointed admin should not have the ability to remove/demote the "main/owner" admin. Only the "main/owner" admin or a higher-level user should be able to perform this action.

**Additional context**
This bug allows a user who has been granted admin privileges to remove/demote the "main/owner" admin, which could lead to unauthorized changes and potential misuse of the Chibisafe instance.

**Comment by Pitu** [comment]
Thanks for the write up, this is definitely something we're looking forward to fix in the very short term

**Comment by Pitu** [comment]
This has been fixed now by changing the logic a little bit. 
In the past there were only admins and users, but now there's also owner. The owner role is the only role that can promote/demote users to admins, effectively making it impossible for admins to demote each other or the owner.

**Comment by 7zx** [comment]
thanks!
