### ISSUE TITLE
[BUG] The light theme looks bad

### ISSUE THREAD

**Issue by eai04191** [chibisafe/chibisafe#434]
**Screenshots**

<details>
<summary>Details</summary>

![localhost_24424_ (2)](https://github.com/chibisafe/chibisafe/assets/3516343/195cb8b6-eab3-4c85-9368-0f444ee781e2)

![localhost_24424_ (1)](https://github.com/chibisafe/chibisafe/assets/3516343/0dc59fcf-0c0f-4436-8deb-d8773bd6429d)

![localhost_24424_dashboard_uploads (1)](https://github.com/chibisafe/chibisafe/assets/3516343/d5f7ee22-6180-40ff-acbe-23811cae1eb2)

![localhost_24424_dashboard_uploads (2)](https://github.com/chibisafe/chibisafe/assets/3516343/732bdb0d-726c-4473-9479-58d74e392410)

![localhost_24424_dashboard_uploads (3)](https://github.com/chibisafe/chibisafe/assets/3516343/caa5e13b-5f3d-42c6-b81a-ae98c03eae38)

</details>

**Describe the bug**
When users view your site in the light theme, the text and label colors are very close to the background color and can be difficult to read.

**To Reproduce**
1. Simulate `prefers-color-scheme` to `light` to open website (or just use OS with light theme)

**Expected behavior**
Text should be clearly readable in all environments.

**Additional context**
It may be difficult to support both themes, especially on landing pages, since the administrator can set any background image he/she wants.
If there are not many users who want the light theme, it may be better to simply support only the dark theme rather than expanding support for the light theme.

**Comment by Pitu** [comment]
Since we're planning on letting the admin customize a lot of colors the sensible approach is to only support dark theme and let users theme it as it pleases

**Comment by Pitu** [comment]
This should be fixed now!
