### ISSUE TITLE
[BUG] - Can’t see image thumbnails in Dashboard

### ISSUE THREAD

**Issue by BrooklynMan** [chibisafe/chibisafe#457]
**Describe the bug**
Can’t see image thumbnails in user dashboard

**To Reproduce**
1. Log in
2. Browse to uploads
3. select “Grid View"

**Expected behavior**
To see image thumbnails in a grid

**Screenshots**
<img width="994" alt="Screenshot 2023-07-30 at 4 07 05 PM" src="https://github.com/chibisafe/chibisafe/assets/5836168/c662abb9-efd3-4230-8920-8c4c74ba9e8d">

**Additional context**
I have replicated the issue in Safari and Firefox for macOS and Safari of iOS. This happens with to without any content blockers loaded and even after clearing all website data and reloading.

**Comment by Pitu** [comment]
Thank you for reporting this.
Unfortunately, it seems that chibisafe version you are running based on your screenshot is either v2 or v3, which has been deprecated. There is a migration script from v3 to v4, and from v4 to v5 but honestly speaking I can't guarantee that it works correctly as the project changed so much in the last couple of years. Your best bet is to either make a backup of the db and try the migration or start from scratch on the new version of chibisafe.
