### ISSUE TITLE
[FEATURE REQUEST] Enhanced text handling

### ISSUE THREAD

**Issue by LostAndDead** [chibisafe/chibisafe#461]
**Describe the solution you'd like**
Pastebin/enhanced text upload, syntax highlighting, and language choices

**Additional context**
Text uploads are boring and look boring a new text upload window allows the pasting of big bits of text and a choice of languages (c++, js, html, css, py, java, ect...). Which when viewed highlights the text, like Pastebin but incorporated into Chibisafe. Pretty sure there are dozens of packages for text highlighting, Basically just an idea to spruce up the text upload side of Chibisafe

**Comment by Pitu** [comment]
This has been implemented and released already.
