### ISSUE TITLE
[BUG] Chibisafe fails with ETXTBSY on docker.

### ISSUE THREAD

**Issue by xGigaa** [chibisafe/chibisafe#491]
**Describe the bug**
When I try to run the newest version of Chibisafe on docker it fails with ETXTBSY.
This seems to happen with anything newer than v5.2.4.

**To Reproduce**
1. Edit my docker-compose.yaml
2. Change image to `image: chibisafe/chibisafe:v5.3.2`
3. Run `docker-compose up`
4. Container exits with ETXTBSY

**Expected behavior**
I expect chibisafe to not fail on ETXTBSY

**Screenshots**

**Additional context**
Full error:
```
$ docker-compose up
Recreating chibisafe ... done
Attaching to chibisafe
chibisafe    | Internal Error: spawn ETXTBSY
chibisafe    |     at ChildProcess.spawn (node:internal/child_process:414:11)
chibisafe    |     at Object.spawn (node:child_process:761:9)
chibisafe    |     at lU (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:4:7031)
chibisafe    |     at zf.implementation (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:392:17799)
chibisafe    |     at zf.exec (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:395:1585)
chibisafe    |     at zf.run (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:395:1756)
chibisafe    |     at mV (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:401:6331)
chibisafe    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chibisafe    |     at async gke (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:403:16)
chibisafe    |     at async o (/home/node/chibisafe/.yarn/releases/yarn-3.6.0.cjs:403:146)
```

docker-compose.yaml file:
```
$ cat docker-compose.yml
version: "3.7"

services:
  chibisafe:
#    image: chibisafe/chibisafe:v5.2.4
    image: chibisafe/chibisafe:v5.3.2
    container_name: chibisafe
    volumes:
      - ./data/database:/home/node/chibisafe/database:rw
      - ./data/uploads:/home/node/chibisafe/uploads:rw
      - ./data/logs:/home/node/chibisafe/logs:rw
    networks:
      main:
    restart: unless-stopped
networks:
  main:
    external: true
```

**Comment by Pitu** [comment]
@xGigaa what kind of environment are you running chibisafe on? What type of architecture?

This is very odd and not something we've encountered before, in fact there are several people running the latest image without issues, so I wonder if it has to be with your environment.

**Comment by xGigaa** [comment]
Hmm, nothing too unusual.
Debian Bookworm x64 on a i7-5820K.
Docker version 20.10.17+dfsg1
Docker-compose version 1.29.2

**Comment by xGigaa** [comment]
Okey I think I figured it out. 
I stumbled over this Issue, https://github.com/nodejs/node/issues/48444
One of the suggestions were to update docker so I did and after a reboot it just works...
Not sure if it was the old docker version or something else but regardless the issue is fixed.
