### ISSUE TITLE
[BUG] Albums don't update the contents on page load and require a manual refresh.

### ISSUE THREAD

**Issue by rossiscool123** [chibisafe/chibisafe#501]
**Describe the bug**
Albums don't update the contents on page load and require a manual refresh in order to fetch the correct files tagged in the album.

**To Reproduce**
1. Create two albums and upload a image to each one.
2. Navigate between the albums and the same image will appear until you manually refresh the page.

**Expected behavior**
For the contents to automatically update without the user needing to refresh the page

**Comment by rossiscool123** [comment]
chibisafe v5.3.4 deployed with docker-compose.

**Comment by Pitu** [comment]
Thanks for flagging this @rossiscool123, the new release is being published right now so it will be available in a few minutes.
