### ISSUE TITLE
[BUG] Documents without preview cannot access the actions panel

### ISSUE THREAD

**Issue by rossiscool123** [chibisafe/chibisafe#504]
**Describe the bug**
Files that are not photo/video do not display the action panel as the width is too small, temporary work around is to set the min-width to like 1000px in my test
**To Reproduce**
1. Upload a file that's not a video/photo, my example was a Photoshop document.
2. Click on the file once its uploaded and the action panel will be too small to properly use.

**Expected behavior**
The width should be tall enough to view the action panel

https://github.com/chibisafe/chibisafe/assets/62076535/dd2f1abc-32e9-400b-a681-054f85e65f7b

**Video**

**Additional context**

**Comment by Pitu** [comment]
>The width should be tall enough to view the action panel

You got me there for a second. I was looking at the video and not understanding what you meant, but now it's clear. It's not the width, but the height. 

I'll whip up a fix soon and let you know.
Thanks for reporting this issue!

**Comment by rossiscool123** [comment]
Yeah I meant height. 😋

**Comment by Pitu** [comment]
Thanks for reporting, it's now been fixed
