### ISSUE TITLE
[BUG] Snippets word-wrap 

### ISSUE THREAD

**Issue by rossiscool123** [chibisafe/chibisafe#505]
**Describe the bug**
Snippets go out the bounds of the screen where word-wrap should apply if its close to the border.

**To Reproduce**
1. Create a snippet that's very long in length and save it, result should be the same as the screenshot attached.

**Expected behavior**
Word wrap should correctly prevent the text from going out of the bounds of the display.

**Screenshots**
![image](https://github.com/chibisafe/chibisafe/assets/62076535/894b4d9c-8fa4-48ce-8ae5-00f9a7a68789)

**Comment by Pitu** [comment]
Thanks for reporting, it's now been fixed
