### ISSUE TITLE
[BUG] blocked file extensions can be uploaded

### ISSUE THREAD

**Issue by 7zx** [chibisafe/chibisafe#510]
I discovered an issue related to the file upload functionality on my instance. Currently, the system is configured to block certain file extensions, specifically ".exe" files. However, I observed that I was able to successfully upload a file with the ".exe" extension, indicating a potential bypass in the blocking mechanism.

**Comment by Pitu** [comment]
Fixed in https://github.com/chibisafe/chibisafe/pull/512
