### ISSUE TITLE
[FEATURE REQUEST] Listing original filenames in list-view / Downloading to original filename

### ISSUE THREAD

**Issue by NOCx420** [chibisafe/chibisafe#518]
**Is your feature request related to a problem? Please describe.**
I'm running a chibisafe instance for multiple users and it's sometimes very time consuming trying to find a specific file. For example, in list view, clicking on all 30 something files with the .zip extension until you find what you are looking for. Same goes for downloading uploaded files. If you don't rename them and organize them actively, you will quickly lose track of which file is which. 

**Describe the solution you'd like**
It would be nice to have a column for the original filenames in the list view for uploads and to have a toggle in the settings to be able to download files as their original filenames. The latter could be achieved by setting the filename in the Content-Disposition header.

**Additional context**
For the filenames it could look something like this:
![screenshot](https://github.com/chibisafe/chibisafe/assets/56538139/2c1d41e3-42c0-4290-901c-f149dc558a22)

**Comment by Pitu** [comment]
Thank you for bringing this up.
We have to think more about being able to let users download files with the original filename as it can be sensitive data so it has to be limited to the owner, but then again it would be nice to be able to share a file with the original filename too. So we'll see how to tackle this soon.

**Comment by iwa** [comment]
would love to see original filename download happening! if possible could it be a per-upload setting? like a toggle, on by default, on the upload page, or smth?
