### ISSUE TITLE
[FEATURE REQUEST] is there an existing android app 

### ISSUE THREAD

**Issue by lazee486** [chibisafe/chibisafe#522]
**Is your feature request related to a problem? Please describe.**
fireox extension works great, looking for something similiar from android, an app can share to etc

**Describe the solution you'd like**
a basic android app or an existing app i can share to

**Additional context**
something that auto uploads all screenshots would be great, but im more after any image or video I find share to my chibisafe...

**Comment by Pitu** [comment]
To my knowledge there is none.
There was only a shortcut for iOS that lets you upload, but I'm not aware of anything of the sorts for Android at the moment
