### ISSUE TITLE
[FEATURE REQUEST] Customize the homepage

### ISSUE THREAD

**Issue by lazee486** [chibisafe/chibisafe#523]
**Is your feature request related to a problem? Please describe.**
frustrated that I cant change the text on the Home page...sorry if i just cant find where.

**Describe the solution you'd like**
Under settings a place to edit the text on the start page

**Additional context**
just looking to customize :)

**Comment by Pitu** [comment]
This is something we want to add to chibisafe but haven't had the opportunity yet. 
The idea is, and always was, to try and let users customize their instance as much as possible without breaking functionality.

If you really want to customize it right now, the way to do it would be to not use docker, clone the repo, make modifications to `packages/frontend/src/pages/index.vue` (or any other), build chibisafe, and then start it. 

Keep in mind that by doing so, you are potentially breaking the `git pull` command for future updates as we will most likely change things on those files eventually.

**Comment by TheDogHusky** [comment]
Additionnal info i'd like to add:
Customizing the page fully to like show a page saying "Private storage server" with a login button (gross idea but something like that) for like if you use an instance for yourself and not publicly. And if you are connected, show the normal page or a page without the FAQ, Features and all just the upload area and navbar

**Comment by clemone210** [comment]
second the idea to create custom upload page or at lease customize the current version.
Even a simple version would be great to not irritate non-tech users.

**Comment by Pitu** [comment]
You can already kinda do this with the customization settings in the dashboard
![image](https://github.com/chibisafe/chibisafe/assets/7425261/4f7a6029-ad80-4f1f-8753-09034b188b9c)

**Comment by Pitu** [comment]
> > You can already kinda do this with the customization settings in the dashboard

> I just pulled the latest docker compose version. Under cust. I dont have this toogle.

Interesting. Migration should've been applied automatically; would you mind sharing the logs by going to the dashboard > settings and clicking on the download button?

**Comment by Pitu** [comment]
Closing since no response for 2 weeks

**Comment by clemone210** [comment]
Did not see the notification.
Can confirm, working now.
