### ISSUE TITLE
[BUG] Build error

### ISSUE THREAD

**Issue by clabnet** [chibisafe/chibisafe#530]
**Describe the bug**
Please refer to request [528](https://github.com/chibisafe/chibisafe/issues/528)
Clone your latest repo Commit: c7266919614106a3f8b1f431f3006a6a71469280
Install with YARN on my machine. (I use normally PNPM, vite and esbuild)

**To Reproduce**
Please see [this log](https://pastebin.com/SU6VHYQd) 

**Expected behavior**
A build running app

**Comment by Pitu** [comment]
@clabnet could you please share your node and yarn versions?

**Comment by clabnet** [comment]
@Pitu 

npx envinfo --system --binaries --browsers
```
  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 12.41 GB / 31.85 GB
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
```

**Comment by Pitu** [comment]
@clabnet I believe the reason is you are using Yarn 1, when the project uses Yarn 3. Could you try upgrading your version and trying again to see if it solves the issue or we need to dig deeper?

**Comment by clabnet** [comment]
@Pitu   I have upgraded Yarn to v4.02. Unfortunately there are always errors.

> chibisafe@5.3.8 build D:\_POMINI\labs\chibisafe
> turbo run build
╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                  Update available v1.10.14 ≫ v1.11.2                  │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.11.2    │
│               Run "npx @turbo/codemod update" to update               │
│                                                                       │
│     Follow @turborepo for updates: https://twitter.com/turborepo      │
╰───────────────────────────────────────────────────────────────────────╯
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed.
        To quickly resolve the issue, try running:
        - $ turbo daemon clean

        To debug further - please ensure the following:
        - the process identified by the pid in the file at C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\turbod\2a83e6c719043f75\turbod.pid is not running, and remove C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\turbod\2a83e6c719043f75\turbod.pid
        - check the logs at C:\Users\claudio.barca\AppData\Roaming\turborepo\data\logs\2a83e6c719043f75-chibisafe.log
        - the unix domain socket at C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\turbod\2a83e6c719043f75\turbod.sock has been removed

        You can also run without the daemon process by passing --no-daemon
• Packages in scope: @chibisafe/backend, @chibisafe/migration, @chibisafe/website
• Running build in 3 packages
• Remote caching disabled
@chibisafe/backend:build: cache miss, executing 55cbee8745ee5925
@chibisafe/website:build: cache miss, executing 8dca7ab43c32b205
@chibisafe/backend:build: src/routes/admin/files/GetFiles.ts(21,31): error TS2694: Namespace '"D:/_POMINI/labs/chibisafe/node_modules/.prisma/client/index".Prisma' has no exported member 'filesCountArgs'.
@chibisafe/backend:build: src/routes/admin/files/GetFiles.ts(26,25): error TS2694: Namespace '"D:/_POMINI/labs/chibisafe/node_modules/.prisma/client/index".Prisma' has no exported member 'filesFindManyArgs'.
@chibisafe/backend:build: src/routes/admin/users/Demote.ts(36,24): error TS7006: Parameter 'role' implicitly has an 'any' type.
@chibisafe/backend:build: src/routes/admin/users/Disable.ts(37,20): error TS7006: Parameter 'role' implicitly has an 'any' type.
@chibisafe/backend:build: src/routes/admin/users/Enable.ts(37,20): error TS7006: Parameter 'role' implicitly has an 'any' type.
@chibisafe/backend:build: src/routes/admin/users/Promote.ts(36,23): error TS7006: Parameter 'role' implicitly has an 'any' type.
@chibisafe/backend:build: src/routes/snippet/GetSnippets.ts(33,26): error TS7006: Parameter 'snippet' implicitly has an 'any' type.
@chibisafe/backend:build: src/utils/StatsGenerator.ts(203,24): error TS7006: Parameter 'role' implicitly has an 'any' type.
@chibisafe/backend:build: ERROR: command finished with error: command (D:\_POMINI\labs\chibisafe\packages\backend) yarn run build exited (2)
@chibisafe/website:build: src/components/combobox/Combobox.vue(48,2): error TS2305: Module '"radix-vue"' has no exported member 'ComboboxAnchor'.
@chibisafe/website:build: src/components/ui/select/Select.vue(3,22): error TS2305: Module '"radix-vue"' has no exported member 'useForwardPropsEmits'.
@chibisafe/website:build: src/components/ui/select/SelectContent.vue(8,2): error TS2305: Module '"radix-vue"' has no exported member 'useForwardPropsEmits'.
@chibisafe/website:build: src/components/ui/switch/Switch.vue(2,79): error TS2305: Module '"radix-vue"' has no exported member 'useForwardPropsEmits'.
@chibisafe/website:build: src/components/ui/tabs/Tabs.vue(2,20): error TS2305: Module '"radix-vue"' has no exported member 'useForwardPropsEmits'.
@chibisafe/website:build: src/components/ui/tooltip/Tooltip.vue(2,69): error TS2305: Module '"radix-vue"' has no exported member 'useForwardPropsEmits'.
@chibisafe/website:build: src/components/ui/tooltip/TooltipContent.vue(7,2): error TS2305: Module '"radix-vue"' has no exported member 'useForwardPropsEmits'.
@chibisafe/backend#build: command (D:\_POMINI\labs\chibisafe\packages\backend) yarn run build exited (2)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    13.68s
Failed:    @chibisafe/backend#build

 ERROR  run failed: command  exited (2)
 ELIFECYCLE  Command failed with exit code 2.

**Comment by clabnet** [comment]
Sorry but I dont' use turbo and not yarn use. Only pnpm and esbuild, https://tsup.egoist.dev/#code-splitting

**Comment by Pitu** [comment]
You are doing `yarn install` but `npm run build`.
You also installed Yarn 4 when we are using Yarn 3. 
Now I don't know if these are the reason for the error, but the version of typescript that is getting installed on your system is reporting errors that the version we use on production isn't, and I'm not sure why.

I'll try to go through your logs and fix those, even though they shouldn't be a problem.

**Comment by Pitu** [comment]
@clabnet instead of this
```
PS D:_POMINI\labs\chibisafe> npm run build
```
Could you try building with `yarn build` instead?

**Comment by clabnet** [comment]
@Pitu  
```
PS D:\test\labs\chibisafe> yarn info -A --name-only
├─ @chibisafe/backend@workspace:packages/backend
├─ @chibisafe/migration@workspace:packages/migration
├─ @chibisafe/uploader-client@npm:1.0.10
├─ @chibisafe/uploader-module@npm:1.0.10
├─ @chibisafe/website@workspace:packages/frontend
├─ @clack/prompts@npm:0.6.3
├─ @fastify/cors@npm:8.3.0
├─ @fastify/helmet@npm:11.1.0
├─ @fastify/rate-limit@npm:8.0.3
├─ @fastify/sensible@npm:5.2.0
├─ @fastify/static@npm:6.11.1
├─ @fastify/swagger@npm:8.10.0
├─ @headlessui/vue@npm:1.7.16
├─ @prisma/client@npm:4.16.2
├─ @tailwindcss/forms@npm:0.5.6
├─ @tailwindcss/typography@npm:0.5.10
├─ @tanstack/vue-query@npm:4.35.3
├─ @tanstack/vue-table@npm:8.9.11
├─ @types/adm-zip@npm:0.5.1
├─ @types/bcryptjs@npm:2.4.4
├─ @types/better-sqlite3@npm:7.6.5
├─ @types/cors@npm:2.8.14
├─ @types/fancy-log@npm:2.0.0
├─ @types/file-saver@npm:2.0.5
├─ @types/fluent-ffmpeg@npm:2.1.22
├─ @types/jsonwebtoken@npm:8.5.9
├─ @types/marked@npm:5.0.1
├─ @types/node-schedule@npm:2.1.0
├─ @types/node@npm:20.6.2
├─ @types/proxy-addr@npm:2.0.0
├─ @types/randomstring@npm:1.1.8
├─ @types/sharp@npm:0.30.5
├─ @types/uuid@npm:8.3.4
├─ @vitejs/plugin-vue@npm:4.3.4
├─ @vue/compiler-sfc@npm:3.3.4
├─ @vueuse/components@npm:10.4.1
├─ @vueuse/core@npm:10.4.1
├─ adm-zip@npm:0.5.10
├─ autoprefixer@npm:10.4.15
├─ bcryptjs@npm:2.4.3
├─ better-sqlite3@npm:8.6.0
├─ blake3@npm:2.1.7
├─ chibisafe@workspace:.
├─ class-variance-authority@npm:0.7.0
├─ clsx@npm:2.0.0
├─ cpy-cli@npm:4.2.0
├─ cross-env@npm:7.0.3
├─ dayjs@npm:1.11.9
├─ dotenv@npm:16.3.1
├─ eslint-config-neon@npm:0.1.56
├─ eslint@npm:8.49.0
├─ fastify@npm:4.23.2
├─ ffmpeg-probe@npm:1.0.6
├─ file-saver@npm:2.0.5
├─ file-stream-rotator@npm:1.0.0
├─ fluent-ffmpeg@npm:2.1.2
├─ fs-jetpack@npm:5.1.0
├─ highlight.js@npm:11.8.0
├─ husky@npm:8.0.3
├─ is-ci@npm:3.0.1
├─ jsonwebtoken@npm:8.5.1
├─ live-directory@npm:3.0.3
├─ lookpath@npm:1.2.2
├─ lucide-vue-next@npm:0.256.0
├─ marked@npm:5.1.2
├─ media-chrome@npm:0.16.3
├─ moment@npm:2.29.4
├─ node-schedule@npm:2.1.1
├─ pinia@npm:2.1.6
├─ pino-pretty@npm:10.2.0
├─ pino@npm:8.15.1
├─ postcss-focus-visible@npm:6.0.4
├─ postcss@npm:8.4.29
├─ prettier@npm:2.8.8
├─ prettier@npm:3.0.3
├─ prisma@npm:4.16.2
├─ proxy-addr@npm:2.0.7
├─ radix-vue@npm:1.2.5
├─ randomstring@npm:1.3.0
├─ remove@npm:0.1.5
├─ rimraf@npm:3.0.2
├─ shadcn-vue@npm:0.1.2
├─ sharp@npm:0.30.7
├─ systeminformation@npm:5.21.5
├─ tailwind-merge@npm:1.14.0
├─ tailwindcss-animate@npm:1.0.7
├─ tailwindcss@npm:3.3.3
├─ ts-node@npm:10.9.1
├─ tsc-alias@npm:1.8.7
├─ tsconfig-paths@npm:4.2.0
├─ tsx@npm:3.12.10
├─ turbo@npm:1.11.2
├─ typescript@patch:typescript@npm%3A5.2.2#~builtin<compat/typescript>::version=5.2.2&hash=5da071
├─ unplugin-vue-components@npm:0.25.2
├─ uuid@npm:9.0.1
├─ v-calendar@npm:2.4.1
├─ vite-plugin-html@npm:3.2.0
├─ vite-plugin-pages@npm:0.31.0
├─ vite-tsconfig-paths@npm:4.2.1
├─ vite@npm:4.4.9
├─ vue-demi@npm:0.14.6
├─ vue-meta@npm:3.0.0-alpha.10
├─ vue-router@npm:4.2.4
├─ vue-sonner@npm:0.4.4
├─ vue-tsc@npm:1.8.11
├─ vue@npm:3.3.4
└─ xss@npm:1.0.14
```
P.S. `yarn info -A` is too long output, I hope this will be enough.

**Comment by mzch** [comment]
I have also got the same error.

```
"node": 18.19.0
"yarn": 3.6.0
"OS": Debian 12.4
```

**Comment by Pitu** [comment]
@mzch do you have this issue with the current released version (v5.4.0)?

**Comment by mzch** [comment]
@Pitu yes, build errors happened in v5.4.0 and v5.3.12.

**Comment by Pitu** [comment]
@mzch could you show me the output of `yarn info typescript`?

**Comment by mzch** [comment]
@Pitu Please see below:
```
└─ typescript@patch:typescript@npm%3A5.3.3#~builtin<compat/typescript>::version=5.3.3&hash=5da071
   ├─ Version: 5.3.3
   │
   └─ Exported Binaries
      ├─ tsc
      └─ tsserver
```

**Comment by Pitu** [comment]
Honestly, I'm not sure what the problem is. I've been doing some research and I'm almost positive it has to do with a different version of Typescript being used for whatever reason.

Do you happen to have typescript globally installed maybe?
At this point I would recommend using the Docker image until I can figure out what the problem is unfortunately. Sorry

**Comment by Pitu** [comment]
Closing this as there has not been any replies and we released a new major version.
