### ISSUE TITLE
Is it normal for my friend to manually handle the commits by hand?

### ISSUE THREAD

**Issue by NULL-BITS** [chibisafe/chibisafe#535]
**To Reproduce**
1. Find a friend like him
2. Tell him about GitHub merging
3. He won't care

**Expected behavior**
He will Go insane

**Screenshots**
![Screenshot_20240105_012826_Gallery.jpg](https://github.com/chibisafe/chibisafe/assets/80842080/d2a85a07-4154-4df5-9688-301c3d252a79)

**Additional context**
Help

**Comment by NULL-BITS** [comment]
@NOCx420

**Comment by Pitu** [comment]
I don't think so
