### ISSUE TITLE
[BUG] Big files

### ISSUE THREAD

**Issue by Tresillo2017** [chibisafe/chibisafe#542]
# Describe the bug
While i'm trying to upload a 1.64gb file from share x, I get payload to large error, but when trying to upload it from the web (firefox browser) it just work fine (every post request takes 11.2 seconds, when It's supposed to do 500ms)

# To Reproduce
1. Select a file
2. Click on 'upload with share x'
3. Wait, and see the error

# Expected behavior
To be able to upload files using the share x client.

# Screenshots
## Nginx proxy manager config
```
client_max_body_size  6000M;
proxy_connect_timeout       300;
proxy_send_timeout          300;
proxy_read_timeout          300;
send_timeout                300;

location / {
        proxy_pass http://192.168.1.95:24424;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # http://nginx.org/en/docs/http/websocket.html
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_redirect off;
}
```

## Share X log (url redacted for privacy)
```
Request URL:
https://upload.example.com/api/upload

Status code:
(413) Payload Too Large

Headers:
Connection: keep-alive
Cross-Origin-Opener-Policy: same-origin
Origin-Agent-Cluster: ?1
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=15552000; includeSubDomains,max-age=63072000;includeSubDomains; preload
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 0
vary: Origin
access-control-allow-origin: *
x-ratelimit-limit: 100
x-ratelimit-remaining: 99
x-ratelimit-reset: 1
Content-Length: 74
Content-Type: application/json; charset=utf-8
Date: Sun, 21 Jan 2024 10:45:37 GMT
Server: openresty

Response text:
{"statusCode":413,"error":"Payload Too Large","message":"File is too big"}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection 
```
# Additional context
I'm using Cloudflare, but this service is not proxied (grey cloud).

**Comment by antonioraminhos** [comment]
85.61.43.128
https://share.tomasps.tk/
orange cloud better

**Comment by Tresillo2017** [comment]
> 85.61.43.128 https://share.tomasps.tk/ orange cloud better

Bruh, could you please delete it?, I don't want my ip to be public.

**Comment by antonioraminhos** [comment]
that doesn't matter, chibisafe automatically split the file into chunks

**Comment by Tresillo2017** [comment]
Well, i've tried with orange cloud and I'm getting the same error, I guess is nginx proxy side

**Comment by pilar6195** [comment]
The chunk splitting only works if you use the website. This is due to the client side custom logic required for it to work. So unfortunately using something like ShareX will upload the file normally without splitting the file and therefore be subject to cloudflare's 100MB limit.

**Comment by Tresillo2017** [comment]
I can upload files from the web but it's take to long for the first part of the file to be uploaded. 
![image](https://github.com/chibisafe/chibisafe/assets/56476330/8fea0a07-5dd3-48a6-9eac-3b5e3d78e680)

**Comment by Tresillo2017** [comment]
Happens If I use share x and the local ip addr.

**Comment by Pitu** [comment]
@Tresillo2017 as @pilar6195 said, this is a limitation between ShareX and our upload logic. ShareX doesn't split by chunks but the website does, ultimately making ShareX hit the 100mb per file upload limit that CloudFlare forces upon you.

Other than that, make sure the max file size in nginx is set to a big number.

**Comment by pilar6195** [comment]
@Tresillo2017 to give a bit more detail:

There is the `Chunk Size` and the `Max Size` settings.
The `Chunk Size` is the max size a chunk should be when splitting. The `Max Size` is what the overall max size a file can be.

If you upload a file using the website, the file will be split into chunks if the file is larger than the `Chunk Size`. `Max Size` is used to determine if the overall file size is too large to be uploaded.

If you upload a file outside of the website (like with shareX) then the file gets uploaded normally since chunk uploading would not be possible unless the client supports our implementation. In this case the `Max Size` is ignored and `Chunk Size` is used in its place to determine if a file is too large to be uploaded.

This means if you upload a file with shareX, with or without cloudflare, the file cannot be larger than what `Chunk Size` is set to.

**Comment by Aareksio** [comment]
Isn't limiting the single file upload size to `Chunk Size` instead of `Max Size` something that could be easily changed?

@Tresillo2017 uses proper nginx limit (`client_max_body_size  6000M;`) and does not proxy with CloudFlare. There is no technical limitation that would prevent a larger file to be successfully uploaded. From outsider perspective, only minor conditional changes to file size validation logic are required [here](https://github.com/chibisafe/uploader/blob/main/packages/uploader-module/src/index.ts#L217-L220) and [there](https://github.com/chibisafe/uploader/blob/main/packages/uploader-module/src/index.ts#L247-L248).

**Comment by Tresillo2017** [comment]
I have the following values set to:
- **Chunk size**: 81000000
- **Maz Size**: 7000000000

The thing is that it could be cloudflare but when try to upload files using the internal ip, I get the same error and it can't be cloudflare or nginx.

**Comment by Pitu** [comment]
@Tresillo2017 chaange the chunk size to 7000000000 and try without cloudflare

**Comment by Tresillo2017** [comment]
> @Tresillo2017 change the chunk size to 7000000000 and try without cloudflare

Tried without cloudflare proxy and got the same error, via web.
![image](https://github.com/chibisafe/chibisafe/assets/56476330/901be2ef-4048-41d5-bd7e-78499afc28da)

**Comment by lakema17** [comment]
Can you do me a favor and try setting `client_max_body_size 0`? It seems like an issue with NPM according to [this issue](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/93) where the fix is just disabling the setting altogether.

**Comment by Pitu** [comment]
@Tresillo2017 That error reeks of nginx problem. What @lakema17 suggested might work.

**Comment by Tresillo2017** [comment]
> @Tresillo2017 That error reeks of nginx problem. What @lakema17 suggested might work.

Works on the browser without cloudflare proxy, but takes a while to start the first chunk. (like 5-10s)

**Comment by lakema17** [comment]
> > @Tresillo2017 That error reeks of nginx problem. What @lakema17 suggested might work.
> 
> Works on the browser without cloudflare proxy, but takes a while to start the first chunk. (like 5-10s)

This could be due to proxy requests being buffered by Nginx. You can try disabling the setting by specifying `proxy_request_buffering on;` and testing it, though it is recommended that you keep buffering on for performance and security reasons.

**Comment by Tresillo2017** [comment]
> > > @Tresillo2017 That error reeks of nginx problem. What @lakema17 suggested might work.
> > 
> > 
> > Works on the browser without cloudflare proxy, but takes a while to start the first chunk. (like 5-10s)
> 
> This could be due to proxy requests being buffered by Nginx. You can try disabling the setting by specifying `proxy_request_buffering off;` and testing it, though it is recommended that you keep buffering on for performance and security reasons.

I think it's worse with that parameter
![image](https://github.com/chibisafe/chibisafe/assets/56476330/cd54d6b2-2bbb-468a-9866-e8f881b3757f)

**Comment by Tresillo2017** [comment]
The disk name is `backup`
![image](https://github.com/chibisafe/chibisafe/assets/56476330/430738f1-4a76-42d6-a483-a7be0d3a940a)

**Comment by lakema17** [comment]
Unfortunately bpytop does not show iowait, which is what I was looking for. You can use `top` and monitor the `wa` metric., but it's not as accurate as running benchmarks directly on the disk. You can try changing directory to your disk `backup` and use [this benchmark](https://github.com/masonr/yet-another-bench-script) and disable the other benches except for io `curl -sL yabs.sh | bash -s -- -gin`

**Comment by Tresillo2017** [comment]
![image](https://github.com/chibisafe/chibisafe/assets/56476330/a379be30-38dd-43ad-951f-9290bc2908c4)
It's an hdd btw

**Comment by lakema17** [comment]
Yeah it's highly likely you're running into a HDD bottleneck. The 5 second wait you're seeing seems to be nginx flushing the chunks of data onto the disk. Depending on how your drive is mounted to the filesystem, the 20MB/s (100MB / 5 seconds) approximation is feasible.

**Comment by Tresillo2017** [comment]
I don't remember how it's mounted but that speeds doesn't seem right for an hdd it normally would be 100mbs or something like that. 
-------- Original message --------From: Lake ***@***.***> Date: 1/23/24  10:52 PM  (GMT+01:00) To: chibisafe/chibisafe ***@***.***> Cc: Tomás Palma ***@***.***>, Mention ***@***.***> Subject: Re: [chibisafe/chibisafe] [BUG] Nginx proxy (Issue #542) 
Yeah it's highly likely you're running into a HDD bottleneck. The 5 second wait you're seeing seems to be nginx flushing the chunks of data onto the disk. Depending on how your drive is mounted to the filesystem, the 20MB/s (100MB / 5 seconds) approximation is feasible.

**Comment by lakema17** [comment]
If you look at your benchmark results, it highly depends on the block size of the data being written. You can check your mount settings using `mount | grep "/dev/sdb1"`. And yeah your disk doesn't really look like it does 100MB/s like you think it does

**Comment by Tresillo2017** [comment]
> If you look at your benchmark results, it highly depends on the block size of the data being written. You can check your mount settings using `mount | grep "/dev/sdb1"`. And yeah your disk doesn't really look like it does 100MB/s like you think it does

It's mounted like that.
![image](https://github.com/chibisafe/chibisafe/assets/56476330/0d785955-d7fd-4ded-b174-7dbc50bd5c65)
Should I change the drive location into a network mounted nfs drive? (1tb).

**Comment by Tresillo2017** [comment]
> If you look at your benchmark results, it highly depends on the block size of the data being written. You can check your mount settings using `mount | grep "/dev/sdb1"`. And yeah your disk doesn't really look like it does 100MB/s like you think it does

The thing is that download speeds are really good I have 1gb 
![image](https://github.com/chibisafe/chibisafe/assets/56476330/acf56e26-f455-4585-a2cf-8afc9923c55f)

**Comment by Tresillo2017** [comment]
I can't still upload big files while on local ip. I get `payload to large`. I have to see what's causing that because I have set no file limit on nginx proxy.

**Comment by lakema17** [comment]
> > If you look at your benchmark results, it highly depends on the block size of the data being written. You can check your mount settings using `mount | grep "/dev/sdb1"`. And yeah your disk doesn't really look like it does 100MB/s like you think it does
> 
> The thing is that download speeds are really good I have 1gb ![image](https://private-user-images.githubusercontent.com/56476330/299450842-acf56e26-f455-4585-a2cf-8afc9923c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDQ2NjAsIm5iZiI6MTcwNjE0NDM2MCwicGF0aCI6Ii81NjQ3NjMzMC8yOTk0NTA4NDItYWNmNTZlMjYtZjQ1NS00NTg1LWEyY2YtOGFmYzk5MjNjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAwNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMzJmOWM5MWU1MjNiMThjNWQ3NjljMDRmOGNhYTNhZDk5Y2Q5YjlhYWRmNjU2MTk2ZGY1NDgzNGQzZGFmNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hnNzWamvTTnz-ol112pgubCrw7Q-tra-rfFjpvw4sOI)

48MB/s is not 1Gbps (1 byte is 8 bits, so 48MB/s is approx. 384Mbit/s). Anyways, I wouldn't say it's rare to have a gap between read and write speeds, especially for SSDs, but yeah for hard disk they're usually closer. You could try monitoring disk activity (read and write speeds) as the first chunk is being uploaded, timing how long the disk is active for compared to how long chibi waits for the data to be written. It could be a problem with something else, considering how the wait only happens on the first chunk. I'm not seeing that same wait on my system, so the best I can tell you to do is profile as much of your system as possible while doing the upload. You could also try running chibisafe in debug mode by using `yarn run dev` and see if the logs have anything to give you, but that's a bit more involved and you might want to run a separate, temporary instance for that.

**Comment by Tresillo2017** [comment]
I just tried on a local enviroment with the git repository and not the docker image, and I'm getting the same `payload to big` error while trying to upload directly from sharex. 
Uploading for the web worked fine and fast. I'm thinking the problem is the hdd of the server.

**Comment by lakema17** [comment]
When uploading with ShareX, max file size is limited to your chunk size, if I recall correctly. You could try increasing chunk size or just not use ShareX for large files.

**Comment by Tresillo2017** [comment]
> When uploading with ShareX, max file size is limited to your chunk size, if I recall correctly. You could try increasing chunk size or just not use ShareX for large files.

That's right, I uploaded a 63mb video via sharex and worked fast and without any errors.

**Comment by Tresillo2017** [comment]
Looks like the delay is network side (apart from the disk)
![image](https://github.com/chibisafe/chibisafe/assets/56476330/87e4f2fe-a02a-40e5-9129-666098f528d6)
Uploading from local lower the wait time to 2s while with the domain it was 13s

**Comment by lakema17** [comment]
Can you try uploading to Chibisafe over WAN? Basically just port forward Chibi and try uploading to it using your public_ip:24424
I have a sneaking suspicion it's a reverse proxy issue, but would like some verification.

**Comment by Tresillo2017** [comment]
> Can you try uploading to Chibisafe over WAN? Basically just port forward Chibi and try uploading to it using your public_ip:24424 I have a sneaking suspicion it's a reverse proxy issue, but would like some verification.
> 
> Though I guess you could also run the reverse proxy on port 80 and access it over LAN instead

![image](https://github.com/chibisafe/chibisafe/assets/56476330/893c76ce-125f-468f-92f6-97127d5073c9)
There's a lot of delay when accessing it over the internet.

**Comment by Tresillo2017** [comment]
> That's fine. What's interesting is that we're not seeing the same wait time on the first chunk. I assume you're not using the reverse proxy, so that _might_ be the issue here. Try using NPM again and see if the wait time comes back

This it what happens, it's interesting to see the difference between the first and second chunk
![image](https://github.com/chibisafe/chibisafe/assets/56476330/9ffc922c-4c25-46ef-a736-47886e3f80c6)

**Comment by Tresillo2017** [comment]
Seems to work fine with the latest Ubuntu release 23.10. Now I get 900ms on local

**Comment by Tresillo2017** [comment]
I'm using now ARC browser and it's working really fine. 100ms of response but at the last chunk I got 2.1 minutes.

**Comment by Pitu** [comment]
Feel free to open this issue again if you need
