### ISSUE TITLE
[BUG] PDFs won't open in album; PNGs do

### ISSUE THREAD

**Issue by 7zx** [chibisafe/chibisafe#550]
**Describe the bug**
Clicking on a PDF file within an album, accessed only through the album link, does not open the file. However, clicking on a PNG file within the same album successfully opens the file.

**To Reproduce**

1. Generate an album link
2. Navigate to the album link
3. Click on the PDF file inside that album
4. Attempt to open the PNG file
5. See that the PDF file doesn't open like it should, but the PNG one does

**Expected behavior**
Clicking on the PDF file within the album should open the file, similar to the behavior observed with PNG files.

**Additional context**
Don't know if the issue is only with non-image files like PDFs or if it applies to all non-image file types. Gotta check if other formats have the same problem in the album.

**Comment by Pitu** [comment]
Fixed
