### ISSUE TITLE
[FEATURE REQUEST] Add a tutorial on how to setup it with ShareX

### ISSUE THREAD

**Issue by TheDogHusky** [chibisafe/chibisafe#556]
**Is your feature request related to a problem? Please describe.**
I recently saw Chibisafe, was interested and ran a self-hosted docker one in my VPS. I'm behind NGINX with NGINX Proxy Manager and I've seen that Chibisafe has a support for ShareX. But the issue is: I don't freaking know how does ShareX custom uploaders works and how I can setup it with chibisafe. I know that it has to be on the /api/upload route, post request and with JSON body but IDK what to put as headers, body content and all using Chibisafe's docs and ShareX Custom Uploader tutorial. I've searched all around the internet to maybe find someone doing this but nope. Nobody has ever posted a single thing about chibisafe and sharex.

**Describe the solution you'd like**
I'd like someone to help me on making this work, and probably the Chibisafe team making a markdown file in this repository as a tutorial on how to use shareX to upload screenshots to Chibisafe, with optionally time to live of the file, etc..

**Comment by Pitu** [comment]
@TheDogHusky Go to your dashboard, and right above the log out button there's a link that generates a ShareX config file for you to import directly. 
![image](https://github.com/chibisafe/chibisafe/assets/7425261/b2a8ec0a-fbbb-444c-8005-ff95b40bdba0)

**Comment by TheDogHusky** [comment]
Oh sh*t.. I'm really dumb..
Thanks tho saves me a lot of time, and thanks for your fast reply!
