### ISSUE TITLE
[FEATURE REQUEST] Further background customization

### ISSUE THREAD

**Issue by TheDogHusky** [chibisafe/chibisafe#557]
**Is your feature request related to a problem? Please describe.**
I know this is kinda dumb, but still useful for some people.
I've been putting a custom background image, but I've came accross an issue: 
If the image is too light, then I can't really read or it is horrible to see. And sometimes the image just has too many elements making it disturbing.

**Describe the solution you'd like**
I know not every people knows how to edit a photo and make it darker or blur it so maybe add a little section about background blur, darkness and things like this or just be able to add like some sort of custom css to change the background?

**Comment by 7zx** [comment]
#523

**Comment by Pitu** [comment]
Further background customization is not going to be a thing for now.
Adding css filters and other real time effects make rendering more expensive, so we invite everyone to find the tool they are most familiar with to edit images and then add them as background on chibisafe.
