### ISSUE TITLE
[BUG] Blocked extensions menu is completely broken

### ISSUE THREAD

**Issue by Riven-Spell** [chibisafe/chibisafe#563]
**Describe the bug**

**To Reproduce**
1. Log into admin account
2. Try to remove blocked extensions. No luck. Clicks are ignored.
3. Try to add blocked extensions. No luck. Enter is ignored.
4. Manually set blocked extensions to nothing via API. There is one empty item present in the UI

Tried from Chrome 122.0.6261.70 and Firefox 122

**Expected behavior**

Clicking X should remove items from the list.
Hitting enter should add items to the list.
An empty list shouldn't display a blank item.

**Screenshots**

![Weird extra?](https://chibi.blatant-lizardry.moe/SMBIWu1oBikV.png)
(Not showed: spamming enter)
![Can't add](https://chibi.blatant-lizardry.moe/dY1gY8lBJq8n.gif)
(Not showed: Spamming LMB)
![Can't remove](https://chibi.blatant-lizardry.moe/xx1OX4Xd4vIv.gif)

**Comment by Riven-Spell** [comment]
(afaict: no requests ever make it to the backend)

**Comment by Pitu** [comment]
This should be fixed in the latest release which will be available in a few minutes.
