### ISSUE TITLE
[FEATURE REQUEST] Add folder picker option like WeTransfer

### ISSUE THREAD

**Issue by bludlineaudio** [chibisafe/chibisafe#567]
**Is your feature request related to a problem? Please describe.**
Can't upload folders, I assume it's not yet supported?

**Describe the solution you'd like**
See below

**Additional context**
See below

---

Hi team, great piece of software btw! 🫡🙌

---

I have a feature request please:

It's to do with uploading Whole Folders.
As you can see in the screenshots, it _appears to be_ possible with Chibisafe if you drag-and-drop the folder into the web interface (but nothing actually gets uploaded). 
But the problem with this is there are _some_ people who just would not inherently know how to do this 😒
[WeTransfer](https://wetransfer.com/) makes it very easy by having a separate button `Or select a folder` (in the 2nd screenshot) which lets the user 🥁 select_a_folder 😲. The folder-picker-popup then allows the user to double-click into folders, and when they've chosen the one they keep that one selected and then select `Upload` on the folder-picker-popup.

I'm happy to give some UI suggestions to make space for the `Select a folder` button?

---

I think this might help:
https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker

I also asked ChatGTP and it said this:
_To implement a folder picker functionality on your website, you would need to use the HTML <input> element with the directory attribute. However, it's important to note that the directory picker feature is currently only supported in certain browsers like Chrome and Edge, and its behavior may vary across different operating systems._

_Here's how you can create a folder picker input in HTML:_
```html
<input type="file" id="folderPicker" webkitdirectory directory multiple>
```

---

I'd appreciate it if you could give me a rough estimation of when it might be likely this feature will be added in if you choose to do so, or an explanation of why it won't be added,
Please let me know if there is a more formal way to request features or if there is any other info you'd need from me.

Thanks in advance 🤗

---

**Chibisafe- Drag-and-drop folder into Web UI (doesn't upload folder)**

![image](https://github.com/chibisafe/chibisafe/assets/143179790/63ec9c0b-af34-455d-8f8f-a3a2abb5c3e6)

**Chibisafe- Folder shows but doesn't proceed to upload, no progress is ever shown**

![image](https://github.com/chibisafe/chibisafe/assets/143179790/1ad8c858-d1e7-4e06-9ff0-518194f7628d)

---

**WeTransfer - Folder-picker-popup**

![image](https://github.com/chibisafe/chibisafe/assets/143179790/daffce75-dd03-48a9-8e23-962eb071bfc4)

**Comment by iCrawl** [comment]
Decided against a separate link/button for this.

Simply drag'n'drop a folder though should now work as expected 👍

**Comment by bludlineaudio** [comment]
Devs that actually listen 💯 👌 Noel for president 2024!
Thanks so much mate, that was really quick, I'll check it out 

Btw I am using Docker compose, is there a way for me to deploy the `feat/drag-drop-folder` branch?
I don't really want to have to faff around with creating a custom Docker image so am happy to wait till the feature is in the main branch that I can deploy with `chibisafe/chibisafe:latest`
I know for Android we can use `jitpack.io` to create a build of a custom branch to include in the project as a gradle library dependency, maybe something like that exists for Docker...

**Comment by Pitu** [comment]
> Devs that actually listen 💯 👌 Noel for president 2024! Thanks so much mate, that was really quick, I'll check it out
> 
> Btw I am using Docker compose, is there a way for me to deploy the `feat/drag-drop-folder` branch? I don't really want to have to faff around with creating a custom Docker image so am happy to wait till the feature is in the main branch that I can deploy with `chibisafe/chibisafe:latest` I know for Android we can use `jitpack.io` to create a build of a custom branch to include in the project as a gradle library dependency, maybe something like that exists for Docker...

Sorry that's on me, closed this issue without merging the feature.
I'll merge it now but won't create a new deployment yet, so what you could do instead is build the image yourself with 1 command. For that, edit your `docker-compose.yml` and remmove the `image` property and instead add a `build` property, kinda like follows:

```yml
services:
  chibisafe:
    #image: ghcr.io/chibisafe/chibisafe:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
	...
```

So if you pull from master and run `sudo docker compose up --build -d` you will have the latest version from the repo.
Either that or wait for a new release but that might not happen for a few days
