### ISSUE TITLE
[FEATURE REQUEST] Spectacle support (cover Linux community)

### ISSUE THREAD

**Issue by zacekjakub** [chibisafe/chibisafe#568]
**Is your feature request related to a problem? Please describe.**
I am Linux user, so I don't have ShareX.

**Describe the solution you'd like**
What about supporting Spectacle from KDE or any multiplatform screenshot app?

**Comment by Pitu** [comment]
I don't have KDE so I can't try, but if spectacle supports posting the screenshot to a service via API then chibisafe should work out of the box provided you specify the correct endpoint.

**Comment by zacekjakub** [comment]
Sure, if Spectacle supported API, I would not ask. :) So at this point Linux users are screwed, Imgur, which is implemented is pretty often down.

**Comment by lakema17** [comment]
Sounds like an issue with Spectacle. There's no reason it can't support a generic file uploading API. If it supports Imgur, then it probably can support Chibisafe by changing the endpoint and a couple headers.

**Comment by Pitu** [comment]
This is not an issue with chibisafe, if the app you want to use doesn't support API parameters to upload a picture then there's nothing we can do.
