### ISSUE TITLE
[FEATURE REQUEST] Discord Embeds / Embedding Links

### ISSUE THREAD

**Issue by iiTranquility** [chibisafe/chibisafe#574]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**

I'd like Chibisafe to have embeds on images.
The issue was mentioned in #330 but it seems there was a misunderstanding.
Files are embedded, but not with a title and variables like the image shows.
![image](https://github.com/chibisafe/chibisafe/assets/21291440/86ad4e1a-74bf-4604-8bcd-0afc7cd22b1f)
The above picture is of a Discord embed sent from a webhook from a different project, showing the title embed with various variables.

![image](https://github.com/chibisafe/chibisafe/assets/21291440/1c2eb3b5-60ee-4e4f-9bb4-0e0fd34c910b)
This one is showing the same thing, but with a title and description, also with variables.

**Additional context**

Thank you for the project ;)

**Comment by Pitu** [comment]
Sorry, we won't be adding custom metadata for image linking. We already provide dynamic metadata for albums, short links, snippets and other pages, but won't be going forward with metadata on direct file hits.
