### ISSUE TITLE
[BUG] Something went wrong when viewing anon uploads only in dash

### ISSUE THREAD

**Issue by iiTranquility** [chibisafe/chibisafe#575]
**Describe the bug**

Having an issue with attempting to view anonymous uploads only on the panel.

**To Reproduce**

1. Upload something anonymously (enabling public uploads)
2. Log in as admin
3. Check uploads
4. Turn on "Show anonymous uploads only"
5. "Something went wrong" occurs.

In the web browsers network tab, I get 

```
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Something went wrong"
```

But in Portainer I get

```
[18:29:14.458] ERROR (314): Response doesn't match the schema
[18:29:14.459] ERROR (314): Something went wrong
[18:29:14.460] INFO (314): GET /api/admin/files?page=1&limit=50&publicOnly=true&quarantine=false 500 11ms public.ip.redacted
```

**Expected behavior**
I should be able to view anonymous uploads only without an error.

**Screenshots**

**Additional context**

**Comment by iCrawl** [comment]
Fixed in https://github.com/chibisafe/chibisafe/commit/35ef3a6fc30124b8e1e0146db92bd16ed40de441
