### ISSUE TITLE
[BUG] error when qurantine S3 file "Invalid copy source object key"

### ISSUE THREAD

**Issue by minoplhy** [chibisafe/chibisafe#580]
**Describe the bug**
got the error "Invalid copy source object key" when trying to quarantine a file that is on network storage (S3).

**To Reproduce**
1. Enable Network Storage
2. Upload file
3. click Qurantine on network storage file
4. got error

**Expected behavior**
file should be moved to /qurantine as it is in local storage.

**Screenshots**

**Additional context**
error logs :
```
{"level":50,"time":1711446755196,"pid":297,"err":{"type":"S3ServiceException","message":"Invalid copy source object key","stack":"InvalidArgument: Invalid copy source object key\n    at throwDefaultError (/home/node/chibisafe/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)\n    at /home/node/chibisafe/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5\n    at de_CommandError (/home/node/chibisafe/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/node/chibisafe/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /home/node/chibisafe/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:192:18\n    at async /home/node/chibisafe/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /home/node/chibisafe/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20\n    at async /home/node/chibisafe/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14\n    at async /home/node/chibisafe/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22","name":"InvalidArgument","$fault":"client","$metadata":{"httpStatusCode":400,"requestId":"e344a3831697c330","extendedRequestId":"aOCwx82EbN7Fh5Tm9Zj814jXSOPQ50DI7","attempts":1,"totalRetryDelay":0},"Code":"InvalidArgument"},"msg":"Invalid copy source object key"}
{"level":50,"time":1711446755197,"pid":297,"reqId":"req-98","req":{"method":"POST","url":"/api/admin/file/d3f9d5ac-fe95-43dd-a860-37a83a5a4276/quarantine","hostname":"xxx","remoteAddress":"x.x.x.x","remotePort":60942},"res":{"statusCode":500},"err":{"type":"InternalServerError","message":"Something went wrong","stack":"InternalServerError: Something went wrong\n    at Object.internalServerError (/home/node/chibisafe/node_modules/@fastify/sensible/lib/httpErrors.js:137:19)\n    at _Reply.internalServerError (/home/node/chibisafe/node_modules/@fastify/sensible/index.js:50:42)\n    at Object.<anonymous> (file:///home/node/chibisafe/packages/backend/dist/main.js:81:24)\n    at handleError (/home/node/chibisafe/node_modules/fastify/lib/error-handler.js:65:18)\n    at onErrorHook (/home/node/chibisafe/node_modules/fastify/lib/reply.js:839:5)\n    at Reply.send (/home/node/chibisafe/node_modules/fastify/lib/reply.js:157:5)\n    at /home/node/chibisafe/node_modules/fastify/lib/wrapThenable.js:41:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","explicitInternalServerError":true,"status":500,"statusCode":500,"expose":false},"msg":"Something went wrong"}
{"level":30,"time":1711446755199,"pid":297,"method":"POST","url":"/api/admin/file/d3f9d5ac-fe95-43dd-a860-37a83a5a4276/quarantine","statusCode":500,"responseTime":48,"ip":"x.x.x.x"}
```
```
chibisafe  | [10:24:51.318] ERROR (297): Invalid copy source object key
chibisafe  | [10:24:51.319] ERROR (297): Something went wrong
chibisafe  | [10:24:51.320] INFO (297): POST /api/admin/file/849f4ee1-da42-4567-9590-c3f0cb0e5752/quarantine 500 48ms x.x.x.x
```

**Comment by Pitu** [comment]
https://github.com/chibisafe/chibisafe/pull/582 should fix it, I'm making a new release now.
Let me know if it works for you once the images are published

**Comment by minoplhy** [comment]
> #582 should fix it, I'm making a new release now. Let me know if it works for you once the images are published

qurantine is successful with no error in both the console and audit log. But the file is just gone. I mean, it's really gone. I didn't see the file on both S3 and local. So, i assumed it was deleted somehow

checked on my bucket and on my local, and there's no quarantine folder no file either

**Comment by minoplhy** [comment]
> > > #582 should fix it, I'm making a new release now. Let me know if it works for you once the images are published
> > 
> > 
> > qurantine is successful with no error in both the console and audit log. But the file is just gone. I mean, it's really gone. I didn't see the file on both S3 and local. So, i assumed it was deleted somehow
> > checked on my bucket and on my local, and there's ~no quarantine folder~ no file ~either~
> 
> Does that also happen with newly quarantined files after you updated your instance?

yes, from what I've tested, this is only affected file that has been uploaded to network storage. on local still working fine.

**Comment by minoplhy** [comment]
To avoid confusion, only the network storage file that is newly quarantined is affected.

**Comment by minoplhy** [comment]
I found the source of this problem. Actually, the file didn't get deleted. They just got into a doubling slash and made it unseenable on the S3 client somehow. don't know how other S3 providers handle this, but removing the first "/" from "key" in CopyObjectCommand seems to have solved this issue

![librewolf_k3LTIE4QhN](https://github.com/chibisafe/chibisafe/assets/67270651/4386d698-baeb-4bef-baf4-c27076dfdff7)

**Comment by Pitu** [comment]
You think this might be something specific to Backblaze then?
If so, could you make a note of this if you decide to make a PR with the information on how to set it up for this particular service?

**Comment by iCrawl** [comment]
For testing we use MinIO and it looks like this:

![image](https://github.com/chibisafe/chibisafe/assets/20760160/d6a691d0-1527-4d85-a264-4954fcaeac35)
![image](https://github.com/chibisafe/chibisafe/assets/20760160/3e9f50ed-5e4d-4a94-9915-24c33e34071d)

**Comment by iCrawl** [comment]
Is your bucket name, as defined in the settings maybe with a forward slash? I doubt it, but who knows.

**Comment by minoplhy** [comment]
I'm currently trying this with another provider. btw, if we remove the first "/" from the key to something like 
```ts
Key: `quarantine/${newFileName}`,
```
with things changing on Minio though?

**Comment by iCrawl** [comment]
Ill have to try, but preferably it should work the same on all if we change it.

**Comment by minoplhy** [comment]
tested with Exoscale, this is what i got. They seem to have this problem too.
![image](https://github.com/chibisafe/chibisafe/assets/67270651/02ad5869-13e7-45a1-a9e7-aa142e7395b1)

**Comment by iCrawl** [comment]
It seems to work by just removing the slash in front 🎉

**Comment by Pitu** [comment]
Let me know if it keeps happening, forgot that by merging the PR and mentioning this issue it would auto close it
