### ISSUE TITLE
[FEATURE REQUEST] Copy all links to clipboard

### ISSUE THREAD

**Issue by iiTranquility** [chibisafe/chibisafe#583]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Currently when you upload images, there is a "link" button beside each upload.
I'd like Chibisafe to have the option to "Copy all to clipboard" so if I want to paste 7 images into a ticket, I don't have to get their links manually.
So they'd be in my clipboard as
```
https://example.com/example.png
https://example.com/example.png
https://example.com/example.png
https://example.com/example.png
```

**Additional context**
I appreciate the project and the support you give in Discord :)

**Comment by Pitu** [comment]
Done in 7f728addc6bff45fb58803db8a1e227631b506ca
