### ISSUE TITLE
[FEATURE REQUEST] Using arrow keys when viewing

### ISSUE THREAD

**Issue by iiTranquility** [chibisafe/chibisafe#588]
**Is your feature request related to a problem? Please describe.**

I tried to use arrow keys just now when viewing album pics, but had to instead click off and then click a separate picture to view it.

**Describe the solution you'd like**

I'd like to be able to use arrow keys to browse an album, it'd be much easier to view things :)

**Additional context**

**Comment by Pitu** [comment]
Implemented in https://github.com/chibisafe/chibisafe/pull/617
