### ISSUE TITLE
[BUG] Shared albums do not update once the link has been created

### ISSUE THREAD

**Issue by TiltedKyoso** [chibisafe/chibisafe#594]
**Describe the bug**
When you create a share link for an album, the album displayed with that share link does not update if you add any more images. You need to create a new link to share to show an updated album.

**To Reproduce**
1. Create an album
2. Add an image
3. Create a share link 
4. Now add another image to that album
5. Re-open or refresh the page with your share link
6. The new image does not appear

**Expected behavior**
When you add images to an album with a share link, refreshing the page should show the images you've added, without needing to generate a new link to share.

**Screenshots**
Here's a quick recording of me doing the steps to reproduce and the bug showing
https://i.kyoso.dev/vT5XnkHdpxp0.mp4

**Additional context**
This server is behind CloudFlare, but even with cache purged and developer mode enabled the bug still appears.

**Comment by Pitu** [comment]
Should be fixed in the latest release coming up in a few minutes
