### ISSUE TITLE
[BUG] "Serve Uploads From" banner does not link to the right place

### ISSUE THREAD

**Issue by Riven-Spell** [chibisafe/chibisafe#597]
**Describe the bug**
The banner displayed when "Serve uploads from" is unset links to an invalid page. https://chibi.blatant-lizardry.moe/dashboard/settings is not real, but https://chibi.blatant-lizardry.moe/dashboard/admin/settings is real.

**To Reproduce**
Unset "Service > Serve Uploads From".

**Expected behavior**
Should go to /dashboard/admin/settings, not /dashboard/settings.

**Comment by Pitu** [comment]
Thank you for reporting this, fixed in https://github.com/chibisafe/chibisafe/commit/6697f2eba5533ed01c2e4468b511624f515f3091
