### ISSUE TITLE
[BUG]Cannot Read Properties

### ISSUE THREAD

**Issue by mariushosting** [chibisafe/chibisafe#599]
![cannot read properties](https://github.com/chibisafe/chibisafe/assets/37554361/e846a1ac-1d51-4230-87f6-db5d5b3a9236)

I can't login at all using the default credentials.

**Comment by Pitu** [comment]
Could you share your server logs?
And if possible, the network call from your browser as well by going to DevTools > Network and then clicking on `Sign In` on the page

**Comment by mariushosting** [comment]
I just want to mention I have no issue with the previous version v5.6.9 @Pitu 

This is the compose:

`version: "3.9"
services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    ports:
      - 24424:8001
    restart: on-failure:5

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - /volume1/docker/chibisafe/database:/app/database:rw
      - /volume1/docker/chibisafe/uploads:/app/uploads:rw
      - /volume1/docker/chibisafe/logs:/app/logs:rw
    environment:
      - SERVE_UPLOADS_FROM=http://localhost:24424
    ports:
      - 24423:8000
    restart: on-failure:5`

![test network](https://github.com/chibisafe/chibisafe/assets/37554361/58ee7d82-a765-442c-92de-06c3b8aed6bf)
![Screenshot 2024-04-16 13 26 21](https://github.com/chibisafe/chibisafe/assets/37554361/734ca2f8-8c87-4fcf-89e2-1a562e0f9b65)


**logs from the server container too:**


Prisma schema loaded from src/prisma/schema.prisma
Datasource "db": SQLite database "database.sqlite" at "file:../../../../database/database.sqlite"
13 migrations found in prisma/migrations
No pending migrations to apply.
Prisma schema loaded from src/prisma/schema.prisma
✔ Generated Prisma Client (v5.12.1) to ./../../node_modules/@prisma/client in 173ms
Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```
See other ways of importing Prisma Client: http://pris.ly/d/importing-client
┌────────────────────────────────────────────────────────────────┐
│  Supercharge your Prisma Client with global database caching,  │
│  scalable connection pooling and real-time database events.    │
│  Explore Prisma Accelerate: https://pris.ly/cli/-accelerate    │
│  Explore Prisma Pulse: https://pris.ly/cli/-pulse              │
└────────────────────────────────────────────────────────────────┘
[10:23:30.525] INFO (155): Running Chibisafe v6.0.6
[10:23:30.802] WARN (155): Found route without URL or METHOD - dist/routes/admin/files/Unzip.js
[10:23:30.903] WARN (155): Found route without URL or METHOD - dist/routes/album/ZipAlbum.js
[10:23:30.998] INFO (155): Server listening at http://0.0.0.0:8000
[10:23:31.843] INFO (155): No updates available
[10:23:44.699] INFO (155): Route GET:/ not found
[10:23:44.703] INFO (155): GET / 404 8ms 192.168.224.1 
[10:23:47.225] INFO (155): GET /api/settings 200 6ms 192.168.224.2 
[10:23:47.226] INFO (155): GET /api/settings 200 6ms 192.168.224.2 
[10:23:47.700] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:23:58.272] INFO (155): GET /api/settings 200 3ms 192.168.224.1 
[10:24:00.440] INFO (155): GET /api/settings 200 3ms 192.168.224.1 
[10:24:01.616] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:24:02.172] INFO (155): GET /api/settings 200 4ms 192.168.224.2 
[10:24:36.411] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:24:38.478] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:24:38.554] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:24:45.197] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:25:08.047] INFO (155): GET /api/settings 200 3ms 192.168.224.2 
[10:25:18.997] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:25:57.771] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:25:59.033] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:25:59.112] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:25:59.738] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:25:59.795] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:26:03.384] INFO (155): GET /api/settings 200 2ms 192.168.224.2 
[10:26:18.061] INFO (155): GET /api/settings 200 2ms 192.168.224.2

**Comment by Pitu** [comment]
@mariushosting you are missing the caddy service inside the docker-compose.yml file, that seems you removed manually. Caddy is needed to consolidate both services into 1 accessible port, so I don't know why you removed that.

**Comment by mariushosting** [comment]
@Pitu so let me understand we can't use anymore chibisafe new version? 

We use this previous container v5 on a Synology NAS but looks like is now restricted in some devices.

https://mariushosting.com/how-to-install-chibisafe-on-your-synology-nas/

**Comment by traliotube** [comment]
@Pitu I use this compose file

``` yaml
version: "3.7"
services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    ports:
      - 24424:8001
    restart: unless-stopped
  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - /mnt/chibisafe/database:/app/database:rw
      - /mnt/chibisafe/uploads:/app/uploads:rw
      - /mnt/chibisafe/logs:/app/logs:rw
    environment:
      - SERVE_UPLOADS_FROM=http://http://192.168.0.227:24424
    expose:
      - 8000
    restart: unless-stopped
```

I understand I have removed the caddy service manually, as I do not want a separate service just for a proxy. I use Cloudflare tunnels to I integrate my services to a domain.

**Comment by lakema17** [comment]
> I understand I have removed the caddy service manually, as I do not want a separate service just for a proxy. I use Cloudflare tunnels to I integrate my services to a domain.

@traliotube Stop removing Caddy. It's not acting as a proxy for your domain, it's supposed to be an internal proxy for Chibisafe services.

**Comment by lakema17** [comment]
> > > I understand I have removed the caddy service manually, as I do not want a separate service just for a proxy. I use Cloudflare tunnels to I integrate my services to a domain.
> > 
> > 
> > @traliotube Stop removing Caddy. It's not acting as a proxy for your domain, it's supposed to be an internal proxy for Chibisafe services.
> 
> Done, but should I change the `BASE_URL` env variable of the caddy service to my final domain, or leave it as it is

You can leave it as is. @mariushosting this also applies in your case. You'll also have to make note of creating the Caddyfile for the docker stack to mount.

**Comment by traliotube** [comment]
@lakema17 but the login from my Cloudflare tunneled (proxied) URL if not working. I can easily login if I use my local IP address, but it is not possible from my actual public URL, the base URL from the settings of the app is set with the public domain address.

**Comment by lakema17** [comment]
> @lakema17 but the login from my Cloudflare tunneled (proxied) URL if not working. I can easily login if I use my local IP address, but it is not possible from my actual public URL, the base URL from the settings of the app is set with the public domain address.

What does your compose file look like with all the services running?

**Comment by traliotube** [comment]
Edit: Accounts created using Local IP cannot be logged in using the public url (including default admin)

**Comment by traliotube** [comment]
Edit: Accounts created using Local IP cannot be logged in using the public URL (including default admin)
Accounts created using Public URL, cannot be loggin in with the local IP.

In both the cases the error is `Wrong Username or Password`

**Comment by lakema17** [comment]
> Edit: Accounts created using Local IP cannot be logged in using the public URL (including default admin) Accounts created using Public URL, cannot be loggin in with the local IP.
> 
> In both the cases the error is `Wrong Username or Password`

That seems like an issue where your CF tunnel might be pointed to the wrong instance. Are you sure you don't have a separate Chibisafe instance running? Perhaps a v5 that you currently have deployed?

**Comment by lakema17** [comment]
Yeah that looks like it's working as intended. You can probably inspect chibisafe_server and see that it's also serving the API properly. In this case it seems like you're just doing something wrong that I can't really pinpoint. If the API and frontend server both work, then I don't see why auth would just refuse to work. You can double check `chibisafe_server` logs anyways and see what's up

**Comment by traliotube** [comment]
The auth works, but I cannot login the main default admin account using the CF URL

**Comment by traliotube** [comment]
> Yeah that looks like it's working as intended. You can probably inspect chibisafe_server and see that it's also serving the API properly. In this case it seems like you're just doing something wrong that I can't really pinpoint. If the API and frontend server both work, then I don't see why auth would just refuse to work. You can double check `chibisafe_server` logs anyways and see what's up

Just did a fresh install, everything is working now, Thanks for your quick responses and help!

**Comment by lakema17** [comment]
> > Yeah that looks like it's working as intended. You can probably inspect chibisafe_server and see that it's also serving the API properly. In this case it seems like you're just doing something wrong that I can't really pinpoint. If the API and frontend server both work, then I don't see why auth would just refuse to work. You can double check `chibisafe_server` logs anyways and see what's up
> 
> Just did a fresh install, everything is working now, Thanks for your quick responses and help!

Nice. You unfortunately just ran into a super weird bug. It is what it is.

**Comment by mariushosting** [comment]
solved.
