### ISSUE TITLE
[FEATURE REQUEST] options to disable Preview generation

### ISSUE THREAD

**Issue by minoplhy** [chibisafe/chibisafe#601]
**Is your feature request related to a problem? Please describe.**
From what I understand, Chibisafe will summon ffmpeg to generate thumbnails and previews if file size is less than 100 MB. but if hosted on small VPS, it can cause a very high load. In this example, ffmpeg processing around 25 MP4 files, most of which are less than 1MB

![YPNPnITVN8](https://github.com/chibisafe/chibisafe/assets/67270651/23ad11a8-161f-400c-b78a-361ab60be1dd)

**Describe the solution you'd like**
It'll be great if there's an option to disable preview generation.

**Comment by lakema17** [comment]
25 MP4s being uploaded at the same time is crazy, but yeah I could get behind an option to disable preview generation for edge cases like this.

**Comment by Pitu** [comment]
Implemented in #647
