### ISSUE TITLE
[BUG] Caddy reports an error, cannot access port 8001

### ISSUE THREAD

**Issue by Jason-2048** [chibisafe/chibisafe#604]
**Describe the bug**
Completely install according to `https://chibisafe.app/guides/running-with-docker`, even the configuration file has not been modified.

**To Reproduce**
After the installation is completed, an error is reported when accessing through the SSH tunnel.

**Expected behavior**
HTTP error code 502.

**Screenshots**

**Additional context**
caddy: 
`{"level":"error","ts":1713267939.9548666,"logger":"http.log.error","msg":"dial tcp 172.18.0.3:8001: connect: connection refused","request":{"remote_ip":"172.18.0.1","remote_port":"51946","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"127.0.0.1:12478","uri":"/","headers":{"Connection":["keep-alive"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\""],"Dnt":["1"],"Accept-Language":["zh-CN,zh;q=0.9,en;q=0.8"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Mode":["navigate"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Sec-Fetch-User":["?1"],"Sec-Fetch-Dest":["document"],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"Sec-Fetch-Site":["cross-site"],"Accept-Encoding":["gzip, deflate, br, zstd"]}},"duration":0.000523063,"status":502,"err_id":"vdv5pidj4","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}`

**Comment by Jason-2048** [comment]
And now I am running docker chibisafe:v5.6.10.

The docker command is 
`docker run -d   --name=chibisafe   -v ./chibisafe/database:/home/node/chibisafe/database:rw   -v ./chibisafe/uploads:/home/node/chibisafe/uploads:rw   -v ./chibisafe/logs:/home/node/chibisafe/logs:rw   -p 24424:8000   --restart unless-stopped   chibisafe/chibisafe:v5.6.10`

I don't know how to migrate to docker-compose since v6.0 added a built-in caddy than v5.0

**Comment by Pitu** [comment]
@Jason-2048 can you show your final docker-compose file and your Caddyfile? You are required to use caddy exactly the way we set it up in v6 without modifications.

**Comment by Jason-2048** [comment]
> @Jason-2048 can you show your final docker-compose file and your Caddyfile? You are required to use caddy exactly the way we set it up in v6 without modifications.

**docker-compose.yml**
`version: "3.7"
 
services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    environment:
      - SERVE_UPLOADS_FROM=http://localhost:24424
    expose:
      - 8000
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/app/uploads:ro
    ports:
      - 24424:80
    environment:
      - BASE_URL=":80"
    restart: unless-stopped
`

**Caddyfile**
`{$BASE_URL} {
        route {
                file_server * {
                                root /app/uploads
                                pass_thru
                }

                @api path /api/*
                reverse_proxy @api http://chibisafe_server:8000 {
                                header_up Host {http.reverse_proxy.upstream.hostport}
                                header_up X-Real-IP {http.request.header.X-Real-IP}
                }

                @docs path /docs*
                reverse_proxy @docs http://chibisafe_server:8000 {
                                header_up Host {http.reverse_proxy.upstream.hostport}
                                header_up X-Real-IP {http.request.header.X-Real-IP}
                }

                reverse_proxy http://chibisafe:8001 {
                                header_up Host {http.reverse_proxy.upstream.hostport}
                                header_up X-Real-IP {http.request.header.X-Real-IP}
                }
        }
}
`

**Comment by lakema17** [comment]
Can you run `docker compose ps` on the directory and see if all services are running fine?

**Comment by Jason-2048** [comment]
> @Jason-2048 can you show your final docker-compose file and your Caddyfile? You are required to use caddy exactly the way we set it up in v6 without modifications.

I found the problem, it was that the Caddyfile used Windows newlines. Everything works fine after running dos2unix.

**Comment by Jason-2048** [comment]
> Can you run `docker compose ps` on the directory and see if all services are running fine?

thx. I found the problem, it was that the Caddyfile used Windows newlines. Everything works fine after running dos2unix.

**Comment by Jason-2048** [comment]
> @Jason-2048 can you show your final docker-compose file and your Caddyfile? You are required to use caddy exactly the way we set it up in v6 without modifications.

I run Nginx on the front end and use Cloudflare proxy. The configuration file refers to v5.0. Hopefully, the documentation can be updated with the Nginx part
```
server {
    listen [::]:80 default_server;
    listen [::]:443 ssl default_server;
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;
    server_tokens off;
    ssl_protocols TLSv1.3;
    ssl_reject_handshake on;
    return 444;
}
server {
    listen [::]:80;
    listen [::]:443 ssl http2;
    listen 80;
    listen 443 ssl http2;
    server_name  example.com;
    server_tokens off;
	
    allow 173.245.48.0/20;
    allow 103.21.244.0/22;
    allow 103.22.200.0/22;
    allow 103.31.4.0/22;
    allow 141.101.64.0/18;
    allow 108.162.192.0/18;
    allow 190.93.240.0/20;
    allow 188.114.96.0/20;
    allow 197.234.240.0/22;
    allow 198.41.128.0/17;
    allow 162.158.0.0/15;
    allow 104.16.0.0/13;
    allow 104.24.0.0/14;
    allow 172.64.0.0/13;
    allow 131.0.72.0/22;  #https://www.cloudflare.com/ips-v4
    allow 2400:cb00::/32;
    allow 2606:4700::/32;
    allow 2803:f800::/32;
    allow 2405:b500::/32;
    allow 2405:8100::/32;
    allow 2a06:98c0::/29;
    allow 2c0f:f248::/32;  #https://www.cloudflare.com/ips-v6
    deny all;
    
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    
    ssl_certificate    /path/to/ssl_fullchain.pem;
    ssl_certificate_key    /path/to/ssl_privkey.pem;
    ssl_protocols TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    error_page 497  https://$host$request_uri;
    
    # security headers
	add_header X-Frame-Options           "SAMEORIGIN" always;
	add_header X-XSS-Protection          "1; mode=block" always;
	add_header X-Content-Type-Options    "nosniff" always;
	add_header Referrer-Policy           "no-referrer-when-downgrade" always;
	add_header Content-Security-Policy   "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'" always;
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

	# . files
	location ~ /\.(?!well-known) {
		deny all;
	}
    
    # reverse proxy
    location / {
        proxy_pass http://127.0.0.1:24424;
        proxy_http_version                 1.1;
		proxy_cache_bypass                 $http_upgrade;

		# Proxy headers
		proxy_set_header Upgrade           $http_upgrade;
		proxy_set_header Connection        "upgrade";
		proxy_set_header Host              $host;
		proxy_set_header X-Real-IP         $remote_addr;
		proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host  $host;
		proxy_set_header X-Forwarded-Port  $server_port;
		proxy_set_header X-NginX-Proxy     true;

		# Proxy timeouts
		proxy_connect_timeout              60s;
		proxy_send_timeout                 60s;
		proxy_read_timeout                 60s;
    }

    # favicon.ico
	location = /favicon.ico {
		log_not_found off;
		access_log    off;
	}

	# robots.txt
	location = /robots.txt {
		log_not_found off;
		access_log    off;
	}

	# gzip
	gzip            on;
	gzip_vary       on;
	gzip_proxied    any;
	gzip_comp_level 6;
	gzip_types      text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
}
```

**Comment by bielej** [comment]
I'm facing a similar issue.
And yes, I've converted the Caddyfile to Unix line endings and I have configured the `Serve Uploads From` setting.
docker-compose:
```
version: "3.7"

services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - /var/docker_volumes/chibisafe/database:/app/database:rw
      - /var/docker_volumes/chibisafe/uploads:/app/uploads:rw
      - /var/docker_volumes/chibisafe/logs:/app/logs:rw
    expose:
      - 8000
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/app/uploads:ro
    ports:
      - 24424:80
    environment:
      - BASE_URL=":80"
    restart: unless-stopped
```
Caddyfile taken from: https://github.com/chibisafe/chibisafe/pull/600
```
{
        servers {
                trusted_proxies static private_ranges
                client_ip_headers X-Forwarded-For X-Real-IP
        }
}

{$BASE_URL} {
        route {
                file_server * {
                        root /app/uploads
                        pass_thru
                }

                @api path /api/*
                reverse_proxy @api http://chibisafe_server:8000 {
                        header_up Host {http.reverse_proxy.upstream.hostport}
                        header_up X-Real-IP {http.request.header.X-Real-IP}
                }

                @docs path /docs*
                reverse_proxy @docs http://chibisafe_server:8000 {
                        header_up Host {http.reverse_proxy.upstream.hostport}
                        header_up X-Real-IP {http.request.header.X-Real-IP}
                }

                reverse_proxy http://chibisafe:8001 {
                        header_up Host {http.reverse_proxy.upstream.hostport}
                        header_up X-Real-IP {http.request.header.X-Real-IP}
                }
        }
}
```
Caddy error log:
```
caddy_1             | {"level":"error","ts":1713616106.6335502,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"chibisafe:8001","duration":0.045684846,"request":{"remote_ip":"172.26.0.1","remote_port":"50618","client_ip":"192.168.0.128","proto":"HTTP/1.1","method":"GET","host":"chibisafe:8001","uri":"/[REDACTED].png","headers":{"X-Forwarded-Proto":["https"],"X-Nginx-Proxy":["true"],"Accept-Language":["pl,en-US;q=0.9,en;q=0.8,pl-PL;q=0.7"],"Sec-Ch-Ua":["\"Not(A:Brand\";v=\"24\", \"Chromium\";v=\"122\""],"Cookie":[],"Sec-Fetch-Mode":["no-cors"],"Accept-Encoding":["gzip, deflate, br"],"Dnt":["1"],"Sec-Ch-Ua-Platform":["\"Windows\""],"X-Forwarded-Port":["443"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["image"],"Sec-Fetch-Site":["same-origin"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"],"Accept":["image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"],"X-Real-Ip":["192.168.0.128"],"X-Forwarded-For":["192.168.0.128, 172.26.0.1"],"X-Forwarded-Host":["[REDACTED]"],"Referer":["https://[REDACTED]/dashboard"]}},"error":"reading: context canceled"}
```
All image URL result in 404.

Nginx config (same as used with v5):
```
server {
    server_name [REDACTED];
    include /etc/nginx/security.conf;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

    location / {
        proxy_pass http: //127.0.0.1:24424;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;

        # Proxy headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-NginX-Proxy true;

        # Proxy timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # security headers
    client_max_body_size 20M;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # . files
    location ~ /\.(?!well-known) {
        deny all;
    }


    listen 443 ssl http2; # managed by Certbot
    ssl_certificate [REDACTED]
    ssl_certificate_key [REDACTED]
}
server {
    listen 80;
    server_name [REDACTED];
    return 301 https: //$server_name$request_uri;
}
```

**Comment by Pitu** [comment]
Your uploads volume in the caddy service is wrong, based on the path you supplied to chibisafe server

**Comment by bielej** [comment]
You're 100% right - thank you.
The path to the `uploads` folder should be the same in both `chibisafe_server` and `caddy`.
