### ISSUE TITLE
[FEATURE REQUEST] Sub-folders (albums within an album)

### ISSUE THREAD

**Issue by tomakorea** [chibisafe/chibisafe#620]
This features comes from a limitation I just encountered. I wanted to create a main Album of a project. But inside this project album I needed to make new sub-folders (or sub albums?) to organize the project (one sub album for background pictures, another one for characters, etc.). However, I couldn't find any way to do that, but I think it would be very useful, especially when public sharing is needed.

Thank you for your work

**Comment by Pitu** [comment]
This is something we won't be pursuing for the time being.
For now, albums and tags is what we support in this regard and are thinking of improving tags soonish
