### ISSUE TITLE
[FEATURE REQUEST] Image preview Zoom with mousewheel and move with click+cursor

### ISSUE THREAD

**Issue by tomakorea** [chibisafe/chibisafe#621]
During the preview of an image, especially for a large image (4k or over), I feel frustrated I can't zoom in with the mousewheel to see more details and move around with a mouse click + moving the cursor. Would it be possible to do this ? some nice smooth implementation of this feature can be seen in the nanogallery2 project : https://github.com/nanostudio-org/nanogallery2

Thanks !

**Comment by Pitu** [comment]
Implemented in https://github.com/chibisafe/chibisafe/pull/628
