### ISSUE TITLE
[FEATURE REQUEST] community support

### ISSUE THREAD

**Issue by capitalized** [chibisafe/chibisafe#623]
"We could really use a feature to accept donations from users. I know plenty of folks who'd be up for it, and it'd help cover the bills for every Chibisafe owner. Feel free to add any payment method you can code—suggestions include Strike.me, PayPal, Coinbase Commerce, and more."

https://i.pics.rs/IIsOy.png

**Comment by Pitu** [comment]
This is not something we'll be adding for now.
As an alternative, you can build chibisafe and implement these changes in your instance for your users.
