### ISSUE TITLE
[FEATURE REQUEST] E-mail related features (account validation, password reset, change address)

### ISSUE THREAD

**Issue by ivancarlosti** [chibisafe/chibisafe#644]
Email related features, like account validation to make sure that a valid e-mail is added, password reset and email address change of related account using a link on new email address to validate the change. It's also important to provide SMTP setup for servers that cannot send email messages.

**Comment by Pitu** [comment]
This is not something we're interested in pursuing at the time.

**Comment by ivancarlosti** [comment]
No problem, Let me try to do it on a fork :) if success I can share it the solution if u want
