### ISSUE TITLE
[FEATURE REQUEST] Allow destination album selection on homepage

### ISSUE THREAD

**Issue by bielej** [chibisafe/chibisafe#649]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to select the destination album on the homepage (before uploading the files) - like it was on v5.

**Additional context**
![image](https://github.com/chibisafe/chibisafe/assets/11682584/baa6abde-8696-4848-a856-645337a8e867)

**Comment by Pitu** [comment]
This is something that is coming soon.
In the meantime, you can go to your dashboard > albums and drop the files inside the album, or go to dashboard > albums > album and upload from there.

**Comment by Pitu** [comment]
Added on #658
