### ISSUE TITLE
[FEATURE REQUEST] Rules / Terms & Conditions / Privacy Policy (?)

### ISSUE THREAD

**Issue by casualkitten1** [chibisafe/chibisafe#651]
**Is your feature request related to a problem? Please describe.**
I would like a way to create and display rules/terms & conditions and a privacy policy on the homepage. Currently, this isn't possible, which complicates ensuring legal compliance and clear communication with users.

**Describe the solution you'd like**
Add a feature that allows drafting, editing, and displaying rules/terms & conditions and a privacy policy directly within the platform. 

**Additional context**
None.

**Comment by lakema17** [comment]
Legal compliance is a bit important, I'd say lol

**Comment by casualkitten1** [comment]
When I typed "Rules" I meant rules that could be displayed on the side/under as in : 

- Nothing DMCA worthy
- no CSAM (obvious but heh some people tend to forget)
- no x, no y

Because the only worthy option for any abuse would be to contact the abuse infos in the domain whois.
