### ISSUE TITLE
[HELP] Uploaded documents not reachable externally

### ISSUE THREAD

**Issue by NOCx420** [chibisafe/chibisafe#663]
Hello, I just migrated to v6 and everything is up and running. My issue is that all links like "https://files.nocx420.xyz/gohIHpR3dRb3.jpg" are giving me 404 errors.

Happens to new and old uploads, diagnostics and logs are empty, both chibisafe and nginx tell me everything is fine.

The files can still be downloaded from the UI, so the api definitely finds them, it's just that the things aren't accessible via their URLs. Folder and file permissions are also 1:1 in order. 

My serve URL in any case:
![image](https://github.com/chibisafe/chibisafe/assets/56538139/08bd74fe-af8d-43c7-9b70-f8910b674272)

Now I think that the problem somehow lies with nginx. Yes, I'm using nginx, well, trying to at least. And to be honest nothing is spitting errors at me, but it's the only thing non-standard on my installation.

Here's the corresponding nginx configuration:
[chibisafe.txt](https://github.com/user-attachments/files/15536612/chibisafe.txt)

**Comment by NOCx420** [comment]
Okay, it seems like putting my uploads folder to root does fix the issue, but now I have a web dir listing on the main page. >:l

**Comment by CreepsoOff** [comment]
Hello @NOCx420 , I highly recommend [Nginx Proxy Manager](https://github.com/NginxProxyManager/nginx-proxy-manager) if you're struggling, I've set it up and it's working more than perfectly. Hope it helps. And no need to mess with anything, default config with good reverse proxy does the job perfectly!

**Comment by NOCx420** [comment]
> Hello @NOCx420 , I highly recommend [Nginx Proxy Manager](https://github.com/NginxProxyManager/nginx-proxy-manager) if you're struggling, I've set it up and it's working more than perfectly. Hope it helps. And no need to mess with anything, default config with good reverse proxy does the job perfectly!

Looks cool, I'll give it a spin, thanks!

**Comment by lakema17** [comment]
Hello, it seems like your problem is that you're not using try_files for nginx. The try_files directive lets you test for files to serve prior to passing the request through to the proxied service.

**Comment by NOCx420** [comment]
> Hello, it seems like your problem is that you're not using try_files for nginx. The try_files directive lets you test for files to serve prior to passing the request through to the proxied service.

It is what I already tried. Didn't work however. I'm quite content to leaving the two seperated now anyways. But thank you.

**Comment by lakema17** [comment]
I actually looked at your nginx config this time, and the issue is that you have autoindex on. try_files is enough for checking for file uploads without making / an index

**Comment by NOCx420** [comment]
> I actually looked at your nginx config this time, and the issue is that you have autoindex on. try_files is enough for checking for file uploads without making / an index

I had removed autoindex before as well and it had no effect.

**Comment by lakema17** [comment]
Do you have the root folder set to your uploads folder? In your case, /app/uploads should contain "gohIHpR3dRb3.jpg" in order for try_files to see it. Copying what caddy does for chibi using nginx shouldn't be too difficult, it's just a matter of making sure that your environment and configs are correct

**Comment by NOCx420** [comment]
> Do you have the root folder set to your uploads folder? In your case, /app/uploads should contain "gohIHpR3dRb3.jpg" in order for try_files to see it. Copying what caddy does for chibi using nginx shouldn't be too difficult, it's just a matter of making sure that your environment and configs are correct
> 
> edit:
> 
> > Okay, it seems like putting my uploads folder to root does fix the issue, but now I have a web dir listing on the main page. >:l
> 
> Seems like you almost had the right config here, all you had to do was disable autoindex.

Yeah, I tried putting in my uploads directory, but then it would just show it open it as a web directory if I went to /.

**Comment by lakema17** [comment]
That's due to the fact that you had autoindex enabled. If you keep it disabled while having try_files use the reverse proxy as a fallback, it should work as intended.
