### ISSUE TITLE
[FEATURE REQUEST] Enhance File Upload Experience in ChibiSafe

### ISSUE THREAD

**Issue by shwetd19** [chibisafe/chibisafe#664]
Problem Description:
I frequently find myself frustrated when uploading files to ChibiSafe because the process feels slow and lacks feedback. It's hard to know if my files are being uploaded successfully or if I need to wait longer. Additionally, having to upload files one at a time can be tedious, especially when I have multiple files to share.

Describe the Solution You'd Like:
To enhance the file upload experience in ChibiSafe, I suggest introducing several improvements:

- Drag-and-Drop: Simplify uploads by dragging files onto ChibiSafe.
- Upload Progress: Show progress bars to keep users informed during uploads.
- Batch Uploads: Let users upload multiple files at once for quicker uploads.

Additional Context:
Currently, the file upload process in ChibiSafe is somewhat cumbersome due to its lack of modern UI features. While the basic functionality works, the experience could be greatly improved with the suggested enhancements. Here's a mockup of how the drag-and-drop interface could look:

**Comment by Pitu** [comment]
These are all things we already have in chibisafe, are you perhaps running a very old version?

- You can drag and drop as many files as you like
- The progress is shown at the top of the site and if you click on the button it shows even more details
- If you click on the upload button, it lets you select as many files as you want.
