### ISSUE TITLE
[BUG] API auth only works when Cookie: token=... is set

### ISSUE THREAD

**Issue by Kex1016** [chibisafe/chibisafe#668]
**Describe the bug**
Tried to create a shortened link using the API. The auth failed on the script, but went through in the docs page. Tried seeing what the difference was, and found a `token=...` value in the Cookie header of the docs "try me" page. It only worked when I copied that over to the script.

**To Reproduce**
```js
await fetch('https://safe.domain.com/api/link/create', {
  method: 'POST',
  headers: {
      apiKey: `${process.env.CHIBISAFE_KEY}`,
      'Content-Type': 'application/json',
  },
  body: JSON.stringify(shortenerBody),
}); // This should not work
```

```js
await fetch('https://safe.domain.com/api/link/create', {
  method: 'POST',
  headers: {
      apiKey: `${process.env.CHIBISAFE_KEY}`,
      'Content-Type': 'application/json',
      Cookie: `token=${process.env.CHIBISAFE_COOKIE}`
  },
  body: JSON.stringify(shortenerBody),
}); // This should work
```

**Expected behavior**
The API shouldn't refuse my request when I provide the correct key.

**Comment by Kex1016** [comment]
I should probably add that I used Bun's fetch implementation, if that changes anything.

**Comment by iiTranquility** [comment]
Use x-api-key

Kana is going to look into why the docs show apiKey instead of x-api-key

**Comment by Kex1016** [comment]
Thanks, that worked! I guess I can close this.
