### ISSUE TITLE
[FEATURE REQUEST] Sharing existing local files

### ISSUE THREAD

**Issue by Glideh** [chibisafe/chibisafe#674]
I guess this is not exactly the aim of this tool (which is great BTW), but I'd really need to be able to share existing files from the host filesystem.

So additionally to the main upload feature we would have the ability to browse the host filesystem and select a file or a directory to share. The files would then be shared right away without even been copied or encrypted.

I find a lot tools allowing the creation of temporary HTTP links on uploaded files but not a single one for local files, though I often need to share things from my place that would obviously be overkill to be uploaded on the same place...

Am I missing something ?
What do you think ?

**Comment by Pitu** [comment]
I understand what you are looking for but as you mentioned, chibisafe is not the right tool for that.
The furthest you can go with chibisafe relating to local files, is moving a file to the `uploads/live` directory, which is a directory always being watched by chibisafe to process new files that have been added manually from the server.

**Comment by Glideh** [comment]
That's interesting, I'll try that, thanks
