### ISSUE TITLE
Mention blake3 in the file information window.

### ISSUE THREAD

**Issue by HT-7** [chibisafe/chibisafe#686]
**Is your feature request related to a problem? Please describe.**
Currently, the file information window only shows "Hash", without mentioning which hash function it uses. Since blake3 is obscure and not widely used, a user can not guess it without looking at the source code.

**Describe the solution you'd like**
Please mention that it is a "blake3 hash", not just "hash".

**Comment by Pitu** [comment]
Which hashing algorithm chibisafe uses should have no impact in end users using the file information dialog. I agree it could be mentioned in the readme for instance administrators but adding it in the UI serves no purpose.

**Comment by neoromantique** [comment]
@Pitu I would urge to reconsider this as this absolutely serves purpose. 

I needed to confirm if the file has been uploaded correctly (due to unrelated bug), and it took me here to find what hashing algo is used. Especially so, since it is obscure (and I have checked common ones in cli first).
