### ISSUE TITLE
[FEATURE REQUEST] Add lightweight HTML UI for non-JavaScript users and old browsers.

### ISSUE THREAD

**Issue by HT-7** [chibisafe/chibisafe#687]
**Is your feature request related to a problem? Please describe.**

Chibisafe requires JavaScript and a late version of a web browser to run.

In an ideal world, everyone would run the latest version of an operating system and web browser. That is simply not the case.

**Describe the solution you'd like**

Create a lightweight HTML-based upload form that is shown to users who don't run JavaScript or run old browsers. [Pomf](https://github.com/pomf/pomf) has such a feature too. It is called [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement).

**Comment by Pitu** [comment]
We have no plans to implement such a feature for the time being.
Even if you could upload via an html form, there would still be the problem of chunks, the S3 uploads, managing your files, etc.
