### ISSUE TITLE
[FEATURE REQUEST] Add autofocus to username field on login

### ISSUE THREAD

**Issue by molytov** [chibisafe/chibisafe#695]
**Is your feature request related to a problem? Please describe.**
Most login forms tend to focus on the username field so the user can immediately start typing without needing to click or tab to the username field. I use KeepassXC that has an autofill function, which typically does `input username, tab, input password, enter`, and benefits from login sites behaving like this by default. It doesn't seem that the chibisafe login screen has this though.

**Describe the solution you'd like**
Add `autofocus` attribute to username field on login screen.

**Comment by Pitu** [comment]
This is fixed in the new version already which will go live sometime next month so I'll mark it as solved. Feel free to reopen if you encounter this issue again.
