### ISSUE TITLE
[FEATURE REQUEST] edit short-URLs

### ISSUE THREAD

**Issue by cinghialino** [chibisafe/chibisafe#701]
**Is your feature request related to a problem? Please describe.**
I would like to be able to keep a specific link (short url) but being able to tie it to a different file as I change it. The idea comes to mind when you have a static link (thinking of a QR code) to share but you want to be able to not change that QR Code, just the file linked to it (say, a vcard with an updated phone number)

**Describe the solution you'd like**
edit short-urls

**Additional context**
currently you're able only to delete a short url. I assume you can always delete the generated `short url` and then replace it with a new one, but I feel it would be best to be able to edit the `destination URL`

**Comment by Pitu** [comment]
This is not something we'll be implementing anytime soon, sorry
