### ISSUE TITLE
[FEATURE REQUEST] Documentation for Backup of Chibisafe

### ISSUE THREAD

**Issue by Toixinhell** [chibisafe/chibisafe#706]
**Problem**
Unsure how to safely backup the Chibisafe installation (I used Docker).

**Describe the solution you'd like**
 What are the files I have to include. 
 Can it be done while Chibisafe is running?
 After a Backup how would the restore process work?

**Comment by Pitu** [comment]
Ideally you want to stop chibisafe and backup both the `uploads` and `database` folder.
To restore a backup place those 2 folders in the root chibisafe directory and run the service and that should be good enough.
